/* ═══════════════════════════════════════
   Places — Istanbul Place & Food Database
   ═══════════════════════════════════════ */

const places = [
  // ── 1. Ayasofya ──
  {
    id: 'ayasofya',
    name: { tr: 'Ayasofya', en: 'Hagia Sophia', de: 'Hagia Sophia', fr: 'Sainte-Sophie', ar: 'آيا صوفيا', ru: 'Айя-София' },
    category: 'historical',
    district: 'Sultanahmet',
    shortDesc: {
      tr: 'M.S. 537\'de inşa edilen, dünya mimarlık tarihinin en önemli eserlerinden biri.',
      en: 'Built in 537 AD, one of the most important architectural masterpieces in world history.',
      de: 'Erbaut 537 n. Chr., eines der bedeutendsten Bauwerke der Weltgeschichte.',
      fr: 'Construite en 537 apr. J.-C., l\'un des chefs-d\'œuvre architecturaux les plus importants.',
      ar: 'بُنيت عام 537 م، واحدة من أهم التحف المعمارية في تاريخ العالم.',
      ru: 'Построена в 537 году, один из важнейших архитектурных шедевров мировой истории.'
    },
    longDesc: {
      tr: 'Ayasofya, M.S. 537 yılında İmparator Justinianus tarafından inşa ettirilen, dünya mimarlık tarihinin en önemli eserlerinden biridir. Yaklaşık 1000 yıl boyunca Hristiyanlığın en büyük katedrali olarak hizmet vermiş, 1453\'te İstanbul\'un fethiyle camiye dönüştürülmüştür. 481 yıl cami olarak kullanıldıktan sonra 1934\'te müzeye, 2020\'de tekrar camiye çevrilmiştir. Devasa kubbesi 55.6 metre yüksekliğe sahiptir ve döneminin mühendislik harikasıdır. İç mekanında hem Bizans mozaikleri hem de Osmanlı hat sanatı örnekleri bir arada bulunur. Sultanahmet Meydanı\'nın kalbinde yer alan yapı, İstanbul\'un en çok ziyaret edilen turistik mekanıdır.',
      en: 'Hagia Sophia, built in 537 AD by Emperor Justinian, is one of the most important architectural works in world history. It served as the largest cathedral in Christendom for nearly 1,000 years before being converted into a mosque after the Ottoman conquest of Constantinople in 1453. After serving as a mosque for 481 years, it became a museum in 1934 and was reconverted to a mosque in 2020. Its massive dome rises 55.6 meters high and was an engineering marvel of its time. The interior features both Byzantine mosaics and Ottoman calligraphy. Located in the heart of Sultanahmet Square, it is Istanbul\'s most visited landmark.',
      de: 'Die Hagia Sophia wurde 537 n. Chr. von Kaiser Justinian erbaut und ist eines der bedeutendsten Bauwerke der Weltgeschichte. Fast 1.000 Jahre lang diente sie als größte Kathedrale der Christenheit, bevor sie nach der Eroberung Konstantinopels 1453 in eine Moschee umgewandelt wurde. Nach 481 Jahren als Moschee wurde sie 1934 zum Museum und 2020 wieder zur Moschee. Ihre massive Kuppel erreicht eine Höhe von 55,6 Metern. Im Inneren finden sich sowohl byzantinische Mosaiken als auch osmanische Kalligraphie.',
      fr: 'Sainte-Sophie, construite en 537 par l\'empereur Justinien, est l\'une des œuvres architecturales les plus importantes de l\'histoire. Elle a servi de plus grande cathédrale de la chrétienté pendant près de 1 000 ans avant d\'être convertie en mosquée après la conquête ottomane de Constantinople en 1453. Son immense dôme s\'élève à 55,6 mètres de hauteur. L\'intérieur présente des mosaïques byzantines et de la calligraphie ottomane.',
      ar: 'آيا صوفيا، بُنيت عام 537 م بأمر من الإمبراطور جستنيان، وهي واحدة من أهم الأعمال المعمارية في تاريخ العالم. خدمت كأكبر كاتدرائية في العالم المسيحي لنحو ألف عام قبل أن تُحوَّل إلى مسجد بعد الفتح العثماني للقسطنطينية عام 1453. قبتها الضخمة ترتفع 55.6 متراً وكانت أعجوبة هندسية في عصرها. يضم الداخل فسيفساء بيزنطية وخطوطاً عثمانية.',
      ru: 'Айя-София, построенная в 537 году императором Юстинианом, является одним из важнейших архитектурных сооружений мировой истории. Почти 1000 лет она была крупнейшим христианским собором, а после завоевания Константинополя в 1453 году была превращена в мечеть. Её массивный купол возвышается на 55,6 метров. Внутри сочетаются византийские мозаики и османская каллиграфия.'
    },
    rating: 4.9, priceLevel: 0, popularityRank: 1,
    visitHours: { tr: '09:00 - 19:00 (namaz saatlerinde kapalı)', en: '9:00 AM - 7:00 PM (closed during prayer)', de: '09:00 - 19:00 (während des Gebets geschlossen)', fr: '09h00 - 19h00 (fermé pendant la prière)', ar: '09:00 - 19:00 (مغلق أثناء الصلاة)', ru: '09:00 - 19:00 (закрыто во время молитвы)' },
    entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' },
    transport: { tr: 'Tramvay T1 - Sultanahmet durağı', en: 'Tram T1 - Sultanahmet stop', de: 'Straßenbahn T1 - Haltestelle Sultanahmet', fr: 'Tramway T1 - Arrêt Sultanahmet', ar: 'ترام T1 - محطة السلطان أحمد', ru: 'Трамвай T1 - остановка Султанахмет' },
    tips: {
      tr: ['Kalabalıktan kaçınmak için sabah erken gidin', 'Fotoğraf çekimi serbesttir', 'Giriş ücretsizdir', 'Namaz saatlerinde turist girişi kapalıdır'],
      en: ['Visit early morning to avoid crowds', 'Photography is allowed', 'Entrance is free', 'Tourist entry closed during prayer times'],
      de: ['Besuchen Sie früh morgens', 'Fotografieren erlaubt', 'Eintritt frei', 'Während der Gebetszeiten geschlossen'],
      fr: ['Visitez tôt le matin', 'Photographie autorisée', 'Entrée gratuite', 'Fermé pendant les prières'],
      ar: ['قم بالزيارة في الصباح الباكر لتجنب الازدحام', 'التصوير مسموح', 'الدخول مجاني', 'مغلق للسياح أثناء أوقات الصلاة'],
      ru: ['Посетите рано утром', 'Фотографирование разрешено', 'Вход бесплатный', 'Закрыто во время молитв']
    },
    tags: ['history', 'architecture', 'culture', 'museum'],
    emoji: '🕌',
    image: 'url(images/ayasofya.jpg)'
  },

  // ── 2. Sultanahmet Camii ──
  {
    id: 'sultanahmet',
    name: { tr: 'Sultanahmet Camii', en: 'Blue Mosque', de: 'Blaue Moschee', fr: 'Mosquée Bleue', ar: 'جامع السلطان أحمد', ru: 'Голубая мечеть' },
    category: 'historical',
    district: 'Sultanahmet',
    shortDesc: {
      tr: '6 minaresiyle ünlü, İstanbul\'un sembol yapılarından biri.',
      en: 'Famous for its six minarets, one of Istanbul\'s most iconic landmarks.',
      de: 'Berühmt für ihre sechs Minarette, eines der Wahrzeichen Istanbuls.',
      fr: 'Célèbre pour ses six minarets, l\'un des monuments emblématiques d\'Istanbul.',
      ar: 'مشهور بمآذنه الست، أحد أبرز معالم إسطنبول.',
      ru: 'Знаменита шестью минаретами, один из символов Стамбула.'
    },
    longDesc: {
      tr: 'Sultan I. Ahmed tarafından 1609-1616 yılları arasında yaptırılan Sultanahmet Camii, İstanbul\'un en tanınmış simgelerinden biridir. Altı minaresi ve görkemli kubbesiyle dikkat çeker. İç mekanı 20.000\'den fazla İznik çinisiyle süslüdür. Mavi tonlarındaki çiniler nedeniyle dünyada "Mavi Cami" olarak bilinir.',
      en: 'Built between 1609 and 1616 by Sultan Ahmed I, the Blue Mosque is one of Istanbul\'s most recognized symbols. It stands out with its six minarets and grand dome. The interior is decorated with more than 20,000 Iznik tiles in blue tones, giving it its famous name.',
      de: 'Die Blaue Moschee wurde zwischen 1609 und 1616 von Sultan Ahmed I. erbaut. Sie beeindruckt mit sechs Minaretten und einer prächtigen Kuppel. Das Innere ist mit über 20.000 Iznik-Fliesen in Blautönen geschmückt.',
      fr: 'Construite entre 1609 et 1616 par le Sultan Ahmed Ier, la Mosquée Bleue se distingue par ses six minarets et son dôme majestueux. L\'intérieur est décoré de plus de 20 000 carreaux d\'Iznik aux tons bleus.',
      ar: 'بناه السلطان أحمد الأول بين 1609 و1616، ويُعد من أشهر رموز إسطنبول. يتميز بمآذنه الست وقبته الفخمة. يزين الداخل أكثر من 20,000 بلاطة إزنيقية بدرجات اللون الأزرق.',
      ru: 'Голубая мечеть, построенная Султаном Ахмедом I в 1609-1616 годах, — один из самых узнаваемых символов Стамбула. Интерьер украшен более чем 20 000 плитками Изник в голубых тонах.'
    },
    rating: 4.8, priceLevel: 0, popularityRank: 2,
    visitHours: { tr: 'Namaz saatleri dışında açık', en: 'Open outside prayer times', de: 'Außerhalb der Gebetszeiten geöffnet', fr: 'Ouvert en dehors des heures de prière', ar: 'مفتوح خارج أوقات الصلاة', ru: 'Открыто вне времени молитв' },
    entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' },
    transport: { tr: 'Tramvay T1 - Sultanahmet durağı', en: 'Tram T1 - Sultanahmet stop', de: 'Straßenbahn T1 - Sultanahmet', fr: 'Tramway T1 - Sultanahmet', ar: 'ترام T1 - السلطان أحمد', ru: 'Трамвай T1 - Султанахмет' },
    tips: {
      tr: ['Namaz saatlerinde giriş kapalıdır', 'Omuzları ve bacakları örtün', 'Ayakkabıları çıkarın'],
      en: ['Closed during prayer times', 'Cover shoulders and legs', 'Remove shoes'],
      de: ['Während der Gebetszeiten geschlossen', 'Schultern und Beine bedecken', 'Schuhe ausziehen'],
      fr: ['Fermé pendant les prières', 'Couvrir épaules et jambes', 'Retirer les chaussures'],
      ar: ['مغلق أثناء أوقات الصلاة', 'غطِّ الكتفين والساقين', 'اخلع الأحذية'],
      ru: ['Закрыто во время молитв', 'Прикройте плечи и ноги', 'Снимите обувь']
    },
    tags: ['history', 'architecture', 'culture'],
    emoji: '🕌',
    image: 'url(images/sultanahmet.jpg)'
  },

  // ── 3. Topkapı Sarayı ──
  {
    id: 'topkapi',
    name: { tr: 'Topkapı Sarayı', en: 'Topkapi Palace', de: 'Topkapi-Palast', fr: 'Palais de Topkapı', ar: 'قصر طوبكابي', ru: 'Дворец Топкапы' },
    category: 'historical', district: 'Sultanahmet',
    shortDesc: {
      tr: 'Osmanlı İmparatorluğu\'nun 400 yıl boyunca yönetim merkezi.',
      en: 'The administrative center of the Ottoman Empire for 400 years.',
      de: 'Das Verwaltungszentrum des Osmanischen Reiches für 400 Jahre.',
      fr: 'Le centre administratif de l\'Empire ottoman pendant 400 ans.',
      ar: 'المركز الإداري للإمبراطورية العثمانية لمدة 400 عام.',
      ru: 'Административный центр Османской империи 400 лет.'
    },
    longDesc: {
      tr: 'Topkapı Sarayı, 1465-1478 yılları arasında Fatih Sultan Mehmed tarafından yaptırılmış ve yaklaşık 400 yıl boyunca Osmanlı sultanlarının ikametgahı olarak kullanılmıştır. 700.000 metrekarelik alanda dört avlu etrafında organize edilmiş yapılar kompleksidir. Harem bölümü, hazine odaları, kutsal emanetler koleksiyonu ve Boğaz manzaralı bahçeleriyle ziyaretçileri büyüler.',
      en: 'Topkapi Palace was built between 1465-1478 by Sultan Mehmed the Conqueror and served as the residence of Ottoman sultans for approximately 400 years. The complex is organized around four courtyards spanning 700,000 square meters. Its Harem section, treasury rooms, collection of holy relics, and Bosphorus-view gardens enchant visitors.',
      de: 'Der Topkapi-Palast wurde 1465-1478 von Sultan Mehmed dem Eroberer erbaut und diente etwa 400 Jahre als Residenz der osmanischen Sultane.',
      fr: 'Le Palais de Topkapı a été construit entre 1465 et 1478 par le Sultan Mehmed le Conquérant.',
      ar: 'بُني قصر طوبكابي بين 1465-1478 بأمر من السلطان محمد الفاتح وخدم كمقر لسلاطين الدولة العثمانية لنحو 400 عام.',
      ru: 'Дворец Топкапы был построен в 1465-1478 годах Султаном Мехмедом Завоевателем и служил резиденцией османских султанов около 400 лет.'
    },
    rating: 4.8, priceLevel: 2, popularityRank: 3,
    visitHours: { tr: '09:00 - 18:00 (Salı kapalı)', en: '9:00 AM - 6:00 PM (Closed Tuesdays)', de: '09:00 - 18:00 (Dienstags geschlossen)', fr: '09h00 - 18h00 (Fermé le mardi)', ar: '09:00 - 18:00 (مغلق الثلاثاء)', ru: '09:00 - 18:00 (закрыто по вторникам)' },
    entranceFee: { tr: '750 TL', en: '750 TL (~$25)', de: '750 TL (~25€)', fr: '750 TL (~25€)', ar: '750 ليرة تركية', ru: '750 TL (~$25)' },
    transport: { tr: 'Tramvay T1 - Gülhane durağı', en: 'Tram T1 - Gülhane stop', de: 'Straßenbahn T1 - Gülhane', fr: 'Tramway T1 - Gülhane', ar: 'ترام T1 - غولهانه', ru: 'Трамвай T1 - Гюльхане' },
    tips: { tr: ['Harem için ayrı bilet alın', 'En az 3 saat ayırın'], en: ['Buy separate ticket for Harem', 'Plan at least 3 hours'], de: ['Separates Ticket für den Harem'], fr: ['Billet séparé pour le Harem'], ar: ['اشترِ تذكرة منفصلة للحريم'], ru: ['Отдельный билет в Гарем'] },
    tags: ['history', 'culture', 'museum', 'architecture'],
    emoji: '🏰',
    image: 'url(images/topkapi.jpg)'
  },

  // ── 4. Yerebatan Sarnıcı ──
  {
    id: 'yerebatan',
    name: { tr: 'Yerebatan Sarnıcı', en: 'Basilica Cistern', de: 'Cisterna Basilica', fr: 'Citerne Basilique', ar: 'صهريج البازيليك', ru: 'Цистерна Базилика' },
    category: 'historical', district: 'Sultanahmet',
    shortDesc: { tr: '336 sütunuyla yeraltının gizemli sarayı.', en: 'The mysterious underground palace with 336 columns.', de: 'Der geheimnisvolle unterirdische Palast mit 336 Säulen.', fr: 'Le mystérieux palais souterrain aux 336 colonnes.', ar: 'القصر الغامض تحت الأرض بأعمدته الـ 336.', ru: 'Таинственный подземный дворец с 336 колоннами.' },
    longDesc: { tr: 'Yerebatan Sarnıcı, 532 yılında Bizans İmparatoru Justinianus tarafından yaptırılmış devasa bir yeraltı su deposudur. 336 mermer sütun üzerinde yükselen tonozlu tavanıyla "Yeraltı Sarayı" olarak da bilinir. En ünlü özelliği Medusa başlarıdır.', en: 'The Basilica Cistern, built in 532 by Byzantine Emperor Justinian, is a massive underground water reservoir. Known as the "Underground Palace" with 336 marble columns. Its most famous features are two columns resting on Medusa heads.', de: 'Die Cisterna Basilica, 532 von Kaiser Justinian erbaut, ist ein riesiger unterirdischer Wasserspeicher mit 336 Marmorsäulen.', fr: 'La Citerne Basilique, construite en 532 par l\'empereur Justinien, est un immense réservoir souterrain avec 336 colonnes de marbre.', ar: 'صهريج البازيليك بُني عام 532 وهو خزان مياه ضخم تحت الأرض مع 336 عموداً رخامياً.', ru: 'Цистерна Базилика, построенная в 532 году — огромное подземное водохранилище с 336 мраморными колоннами.' },
    rating: 4.7, priceLevel: 2, popularityRank: 4,
    visitHours: { tr: '09:00 - 19:00', en: '9:00 AM - 7:00 PM', de: '09:00 - 19:00', fr: '09h00 - 19h00', ar: '09:00 - 19:00', ru: '09:00 - 19:00' },
    entranceFee: { tr: '600 TL', en: '600 TL (~$20)', de: '600 TL', fr: '600 TL', ar: '600 ليرة', ru: '600 TL' },
    transport: { tr: 'Tramvay T1 - Sultanahmet', en: 'Tram T1 - Sultanahmet', de: 'Straßenbahn T1 - Sultanahmet', fr: 'Tramway T1 - Sultanahmet', ar: 'ترام T1 - السلطان أحمد', ru: 'Трамвай T1 - Султанахмет' },
    tips: { tr: ['Rahat ayakkabı giyin', 'İçerisi serin'], en: ['Wear comfortable shoes', 'It is cool inside'], de: ['Bequeme Schuhe tragen'], fr: ['Portez des chaussures confortables'], ar: ['ارتدِ أحذية مريحة'], ru: ['Наденьте удобную обувь'] },
    tags: ['history', 'architecture', 'underground'],
    emoji: '🏛️',
    image: 'url(images/yerebatan.jpg)'
  },

  // ── 5. Galata Kulesi ──
  {
    id: 'galata',
    name: { tr: 'Galata Kulesi', en: 'Galata Tower', de: 'Galataturm', fr: 'Tour de Galata', ar: 'برج غلطة', ru: 'Галатская башня' },
    category: 'historical', district: 'Beyoğlu',
    shortDesc: { tr: '1348\'den beri İstanbul siluetini süsleyen ikonik kule.', en: 'The iconic tower adorning Istanbul\'s skyline since 1348.', de: 'Der ikonische Turm seit 1348.', fr: 'La tour iconique depuis 1348.', ar: 'البرج الأيقوني منذ 1348.', ru: 'Знаковая башня с 1348 года.' },
    longDesc: { tr: 'Galata Kulesi, 1348 yılında Cenevizliler tarafından inşa edilmiş 67 metre yüksekliğindeki taş kuledir. 360 derece panoramik manzara sunar. Gün batımı manzarası muhteşemdir.', en: 'Galata Tower is a 67-meter stone tower built by the Genoese in 1348. It offers 360-degree panoramic views. The sunset view is spectacular.', de: 'Der Galataturm ist ein 67 Meter hoher Steinturm von 1348 mit 360-Grad-Panorama.', fr: 'La Tour de Galata est une tour de 67 mètres de 1348 avec vue panoramique à 360 degrés.', ar: 'برج غلطة برج حجري بارتفاع 67 متراً من 1348 مع إطلالة بانورامية 360 درجة.', ru: 'Галатская башня — каменная башня 67 метров 1348 года с панорамой 360 градусов.' },
    rating: 4.6, priceLevel: 2, popularityRank: 5,
    visitHours: { tr: '08:30 - 22:00', en: '8:30 AM - 10:00 PM', de: '08:30 - 22:00', fr: '08h30 - 22h00', ar: '08:30 - 22:00', ru: '08:30 - 22:00' },
    entranceFee: { tr: '650 TL', en: '650 TL (~$22)', de: '650 TL', fr: '650 TL', ar: '650 ليرة', ru: '650 TL' },
    transport: { tr: 'Metro M2 - Şişhane', en: 'Metro M2 - Şişhane', de: 'Metro M2 - Şişhane', fr: 'Métro M2 - Şişhane', ar: 'مترو M2 - شيشهانه', ru: 'Метро M2 - Шишхане' },
    tips: { tr: ['Gün batımında gidin'], en: ['Go at sunset'], de: ['Zum Sonnenuntergang gehen'], fr: ['Allez au coucher du soleil'], ar: ['اذهب وقت الغروب'], ru: ['Идите на закате'] },
    tags: ['panorama', 'history', 'photography'],
    emoji: '🗼',
    image: 'url(images/galata.jpg)'
  },

  // ── 6. Dolmabahçe Sarayı ──
  {
    id: 'dolmabahce',
    name: { tr: 'Dolmabahçe Sarayı', en: 'Dolmabahce Palace', de: 'Dolmabahçe-Palast', fr: 'Palais de Dolmabahçe', ar: 'قصر دولما بهجة', ru: 'Дворец Долмабахче' },
    category: 'historical', district: 'Beşiktaş',
    shortDesc: { tr: 'Boğaz kıyısında Osmanlı\'nın son dönem görkemli sarayı.', en: 'The magnificent late Ottoman palace on the Bosphorus.', de: 'Der prächtige spätosmanische Palast am Bosporus.', fr: 'Le magnifique palais ottoman sur le Bosphore.', ar: 'القصر العثماني الفخم على البوسفور.', ru: 'Великолепный позднеосманский дворец на Босфоре.' },
    longDesc: { tr: 'Dolmabahçe Sarayı, 1856 yılında Sultan Abdülmecid tarafından yaptırılmış Avrupa tarzı saraydır. 285 oda ve 46 salon içerir. Atatürk\'ün 10 Kasım 1938\'de vefat ettiği saraydır.', en: 'Dolmabahçe Palace was built in 1856 by Sultan Abdülmecid in European style. It contains 285 rooms and 46 halls. It is where Atatürk passed away on November 10, 1938.', de: 'Der Dolmabahçe-Palast wurde 1856 im europäischen Stil erbaut mit 285 Zimmern.', fr: 'Le Palais de Dolmabahçe fut construit en 1856 dans le style européen avec 285 pièces.', ar: 'بُني قصر دولما بهجة عام 1856 على الطراز الأوروبي ويضم 285 غرفة.', ru: 'Дворец Долмабахче построен в 1856 году в европейском стиле, 285 комнат.' },
    rating: 4.7, priceLevel: 3, popularityRank: 6,
    visitHours: { tr: '09:00 - 16:00 (Pazartesi kapalı)', en: '9:00 AM - 4:00 PM (Closed Mondays)', de: '09:00 - 16:00 (Montags geschlossen)', fr: '09h00 - 16h00 (Fermé le lundi)', ar: '09:00 - 16:00 (مغلق الاثنين)', ru: '09:00 - 16:00 (закрыто по понедельникам)' },
    entranceFee: { tr: '650 TL', en: '650 TL', de: '650 TL', fr: '650 TL', ar: '650 ليرة', ru: '650 TL' },
    transport: { tr: 'Tramvay T1 - Kabataş', en: 'Tram T1 - Kabataş', de: 'Straßenbahn T1 - Kabataş', fr: 'Tramway T1 - Kabataş', ar: 'ترام T1 - كاباتاش', ru: 'Трамвай T1 - Кабаташ' },
    tips: { tr: ['Rehberli tur zorunludur'], en: ['Guided tour is mandatory'], de: ['Führung ist Pflicht'], fr: ['Visite guidée obligatoire'], ar: ['الجولة المرشدة إلزامية'], ru: ['Экскурсия обязательна'] },
    tags: ['history', 'architecture', 'luxury'],
    emoji: '🏰',
    image: 'url(images/dolmabahce.jpg)'
  },

  // ── 7. Kapalıçarşı ──
  {
    id: 'kapalicarsi',
    name: { tr: 'Kapalıçarşı', en: 'Grand Bazaar', de: 'Großer Basar', fr: 'Grand Bazar', ar: 'البازار الكبير', ru: 'Гранд-Базар' },
    category: 'shopping', district: 'Fatih',
    shortDesc: { tr: '1461\'den beri dünyanın en eski kapalı çarşısı.', en: 'The world\'s oldest covered market since 1461.', de: 'Der älteste überdachte Markt seit 1461.', fr: 'Le plus ancien marché couvert depuis 1461.', ar: 'أقدم سوق مغطى منذ 1461.', ru: 'Старейший крытый рынок с 1461 года.' },
    longDesc: { tr: 'Kapalıçarşı, 61 sokak ve 3.000\'den fazla dükkânıyla dünyanın en büyük kapalı çarşılarından biridir. Altın, gümüş, halı, seramik ve el yapımı ürünler bulabilirsiniz. Pazarlık yapmak kültürün parçasıdır.', en: 'The Grand Bazaar has 61 streets and over 3,000 shops. You can find gold, silver, carpets, ceramics and handmade goods. Bargaining is part of the culture.', de: 'Der Große Basar hat 61 Straßen und über 3.000 Geschäfte. Handeln gehört zur Kultur.', fr: 'Le Grand Bazar a 61 rues et plus de 3 000 boutiques. Marchander fait partie de la culture.', ar: 'البازار الكبير يضم 61 شارعاً وأكثر من 3,000 محل. المساومة جزء من الثقافة.', ru: 'Гранд-Базар — 61 улица и более 3 000 магазинов. Торговаться — часть культуры.' },
    rating: 4.5, priceLevel: 1, popularityRank: 7,
    visitHours: { tr: '08:30 - 19:00 (Pazar kapalı)', en: '8:30 AM - 7:00 PM (Closed Sundays)', de: '08:30 - 19:00 (Sonntags geschlossen)', fr: '08h30 - 19h00 (Fermé le dimanche)', ar: '08:30 - 19:00 (مغلق الأحد)', ru: '08:30 - 19:00 (закрыто по воскресеньям)' },
    entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' },
    transport: { tr: 'Tramvay T1 - Beyazıt', en: 'Tram T1 - Beyazıt', de: 'Straßenbahn T1 - Beyazıt', fr: 'Tramway T1 - Beyazıt', ar: 'ترام T1 - بايزيد', ru: 'Трамвай T1 - Беязыт' },
    tips: { tr: ['Pazarlık yapmayı unutmayın'], en: ['Don\'t forget to bargain'], de: ['Vergessen Sie nicht zu handeln'], fr: ['N\'oubliez pas de marchander'], ar: ['لا تنسَ المساومة'], ru: ['Не забудьте торговаться'] },
    tags: ['shopping', 'culture', 'traditional'],
    emoji: '🛍️',
    image: 'url(images/kapalicarsi.jpg)'
  },

  // ── 8-15: Remaining places ──
  { id: 'kizkulesi', name: { tr: 'Kız Kulesi', en: 'Maiden\'s Tower', de: 'Mädchenturm', fr: 'Tour de Léandre', ar: 'برج الفتاة', ru: 'Девичья башня' }, category: 'historical', district: 'Üsküdar', shortDesc: { tr: 'Boğaz\'ın ortasında efsanevi kule.', en: 'Legendary tower in the Bosphorus.', de: 'Legendärer Turm im Bosporus.', fr: 'Tour légendaire dans le Bosphore.', ar: 'برج أسطوري في البوسفور.', ru: 'Легендарная башня в Босфоре.' }, longDesc: { tr: 'Kız Kulesi, Boğaz\'ın ortasında küçük bir adacık üzerinde yükselen romantik simgedir. İlk yapı M.Ö. 5. yüzyıla dayanır. Efsaneye göre bir padişah kızını yılan sokmasından korumak için buraya kapatmıştır.', en: 'Maiden\'s Tower rises on a small islet in the Bosphorus. The first structure dates to the 5th century BC. Legend says a sultan locked his daughter here to protect her from a snake bite.', de: 'Der Mädchenturm auf einer Insel im Bosporus. Der Legende nach sperrte ein Sultan seine Tochter hier ein.', fr: 'La Tour de Léandre sur un îlot du Bosphore. Selon la légende, un sultan y enferma sa fille.', ar: 'برج الفتاة على جزيرة صغيرة في البوسفور. وفقاً للأسطورة حبس سلطان ابنته هنا.', ru: 'Девичья башня на островке в Босфоре. По легенде, султан заточил здесь дочь.' }, rating: 4.5, priceLevel: 2, popularityRank: 8, visitHours: { tr: '09:00 - 18:00', en: '9:00 AM - 6:00 PM', de: '09:00 - 18:00', fr: '09h00 - 18h00', ar: '09:00 - 18:00', ru: '09:00 - 18:00' }, entranceFee: { tr: '200 TL', en: '200 TL', de: '200 TL', fr: '200 TL', ar: '200 ليرة', ru: '200 TL' }, transport: { tr: 'Üsküdar\'dan tekne', en: 'Boat from Üsküdar', de: 'Boot von Üsküdar', fr: 'Bateau depuis Üsküdar', ar: 'قارب من أوسكودار', ru: 'Лодка из Ускюдара' }, tips: { tr: ['Gün batımında gidin'], en: ['Visit at sunset'], de: ['Bei Sonnenuntergang besuchen'], fr: ['Visitez au coucher du soleil'], ar: ['قم بالزيارة عند الغروب'], ru: ['Посетите на закате'] }, tags: ['panorama', 'romantic', 'photography'], emoji: '🏝️', image: 'url(images/kizkulesi.jpg)' },

  { id: 'suleymaniye', name: { tr: 'Süleymaniye Camii', en: 'Suleymaniye Mosque', de: 'Süleymaniye-Moschee', fr: 'Mosquée de Soliman', ar: 'جامع السليمانية', ru: 'Мечеть Сулеймание' }, category: 'historical', district: 'Fatih', shortDesc: { tr: 'Mimar Sinan\'ın ustalık eseri.', en: 'Architect Sinan\'s masterwork.', de: 'Meisterwerk von Architekt Sinan.', fr: 'Chef-d\'œuvre de Sinan.', ar: 'تحفة المعماري سنان.', ru: 'Шедевр архитектора Синана.' }, longDesc: { tr: 'Süleymaniye Camii, 1550-1557 yılları arasında Mimar Sinan tarafından Kanuni Sultan Süleyman adına inşa edilmiştir. Boğaz ve Haliç manzaralı konumuyla İstanbul\'un en etkileyici camilerindendir.', en: 'Built 1550-1557 by Architect Sinan for Sultan Suleiman the Magnificent. One of Istanbul\'s most impressive mosques with Bosphorus and Golden Horn views.', de: 'Erbaut 1550-1557 von Architekt Sinan für Sultan Süleiman den Prächtigen.', fr: 'Construite 1550-1557 par Sinan pour le Sultan Soliman le Magnifique.', ar: 'بُني 1550-1557 على يد المعماري سنان للسلطان سليمان القانوني.', ru: 'Построена в 1550-1557 архитектором Синаном для Султана Сулеймана Великолепного.' }, rating: 4.8, priceLevel: 0, popularityRank: 9, visitHours: { tr: 'Namaz saatleri dışında', en: 'Outside prayer times', de: 'Außerhalb der Gebetszeiten', fr: 'En dehors des prières', ar: 'خارج أوقات الصلاة', ru: 'Вне молитв' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Tramvay T1 - Beyazıt', en: 'Tram T1 - Beyazıt', de: 'Tram T1 - Beyazıt', fr: 'Tram T1 - Beyazıt', ar: 'ترام T1 - بايزيد', ru: 'Трамвай T1 - Беязыт' }, tips: { tr: ['Çay bahçesini deneyin'], en: ['Try the tea garden'], de: ['Probieren Sie den Teegarten'], fr: ['Essayez le jardin de thé'], ar: ['جرب حديقة الشاي'], ru: ['Попробуйте чайный сад'] }, tags: ['history', 'architecture', 'panorama'], emoji: '🕌', image: 'url(images/suleymaniye.jpg)' },

  { id: 'buyukada', name: { tr: 'Büyükada', en: 'Büyükada (Princes\' Islands)', de: 'Büyükada (Prinzeninseln)', fr: 'Büyükada (Îles des Princes)', ar: 'بويوكادا', ru: 'Бююкада' }, category: 'nature', district: 'Adalar', shortDesc: { tr: 'Motorsuz araç cenneti ada.', en: 'A car-free island paradise.', de: 'Ein autofreies Inselparadies.', fr: 'Un paradis sans voiture.', ar: 'جنة خالية من السيارات.', ru: 'Остров без автомобилей.' }, longDesc: { tr: 'Büyükada, Prens Adaları\'nın en büyüğüdür. Motorlu araç yasaktır. Viktoryen ahşap köşkler, çam ormanları ve deniz manzaralarıyla büyüler.', en: 'Büyükada is the largest of the Princes\' Islands. Motor vehicles are banned. Victorian wooden mansions, pine forests, and sea views enchant visitors.', de: 'Büyükada ist die größte der Prinzeninseln. Motorfahrzeuge sind verboten.', fr: 'Büyükada est la plus grande des Îles des Princes. Véhicules motorisés interdits.', ar: 'بويوكادا أكبر جزر الأمراء. السيارات محظورة.', ru: 'Бююкада — крупнейший из Принцевых островов. Автомобили запрещены.' }, rating: 4.6, priceLevel: 1, popularityRank: 10, visitHours: { tr: 'Tüm gün', en: 'All day', de: 'Ganztägig', fr: 'Toute la journée', ar: 'طوال اليوم', ru: 'Весь день' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Kabataş\'tan vapur', en: 'Ferry from Kabataş', de: 'Fähre von Kabataş', fr: 'Ferry depuis Kabataş', ar: 'عبّارة من كاباتاش', ru: 'Паром из Кабаташа' }, tips: { tr: ['Bisiklet kiralayın'], en: ['Rent a bicycle'], de: ['Mieten Sie ein Fahrrad'], fr: ['Louez un vélo'], ar: ['استأجر دراجة'], ru: ['Арендуйте велосипед'] }, tags: ['nature', 'island', 'photography', 'relaxation'], emoji: '🏝️', image: 'url(images/buyukada.jpg)' },

  { id: 'istiklal', name: { tr: 'İstiklal Caddesi', en: 'Istiklal Street', de: 'Istiklal-Straße', fr: 'Avenue Istiklal', ar: 'شارع الاستقلال', ru: 'Истикляль' }, category: 'shopping', district: 'Beyoğlu', shortDesc: { tr: 'İstanbul\'un kalbi, günde 3 milyon kişi.', en: 'Heart of Istanbul, 3 million daily.', de: 'Herz Istanbuls, 3 Millionen täglich.', fr: 'Cœur d\'Istanbul, 3 millions par jour.', ar: 'قلب إسطنبول، 3 ملايين يومياً.', ru: 'Сердце Стамбула, 3 миллиона в день.' }, longDesc: { tr: 'İstiklal Caddesi, Taksim\'den Tünel\'e uzanan 1.4 km\'lik yaya caddesidir. Nostaljik tramvay, mağazalar, kafeler ve gece hayatı.', en: 'Istiklal Street is a 1.4 km pedestrian avenue from Taksim to Tünel. Nostalgic tram, shops, cafes and nightlife.', de: 'Die Istiklal-Straße ist eine 1,4 km lange Fußgängerzone von Taksim bis Tünel.', fr: 'Istiklal est une avenue piétonne de 1,4 km entre Taksim et Tünel.', ar: 'شارع الاستقلال شارع للمشاة بطول 1.4 كم.', ru: 'Истикляль — пешеходный проспект 1,4 км от Таксим до Тюнеля.' }, rating: 4.4, priceLevel: 1, popularityRank: 11, visitHours: { tr: '24 saat', en: '24 hours', de: '24 Stunden', fr: '24 heures', ar: '24 ساعة', ru: '24 часа' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Metro M2 - Taksim', en: 'Metro M2 - Taksim', de: 'Metro M2 - Taksim', fr: 'Métro M2 - Taksim', ar: 'مترو M2 - تقسيم', ru: 'Метро M2 - Таксим' }, tips: { tr: ['Nostaljik tramvaya binin'], en: ['Ride the nostalgic tram'], de: ['Fahren Sie mit der Straßenbahn'], fr: ['Prenez le tramway'], ar: ['اركب الترام'], ru: ['Прокатитесь на трамвае'] }, tags: ['shopping', 'nightlife', 'culture'], emoji: '🚶', image: 'url(images/istiklal.jpg)' },

  { id: 'emirgan', name: { tr: 'Emirgan Korusu', en: 'Emirgan Park', de: 'Emirgan-Park', fr: 'Parc d\'Emirgan', ar: 'حديقة أميرجان', ru: 'Парк Эмирган' }, category: 'nature', district: 'Sarıyer', shortDesc: { tr: 'Lale festivaliyle ünlü park.', en: 'Park famous for Tulip Festival.', de: 'Park berühmt für Tulpenfest.', fr: 'Parc célèbre pour les tulipes.', ar: 'حديقة مشهورة بمهرجان التوليب.', ru: 'Парк, знаменитый Фестивалем тюльпанов.' }, longDesc: { tr: 'Emirgan Korusu, Boğaz kıyısında 47 hektarlık tarihi parkdır. Nisan\'daki Lale Festivali dünya çapında ünlüdür. Üç tarihi köşk ve yürüyüş parkurları içerir.', en: 'Emirgan Park is a 47-hectare historic park on the Bosphorus. The April Tulip Festival is world-renowned. Contains three historic pavilions and walking trails.', de: 'Der Emirgan-Park ist ein 47 Hektar großer historischer Park am Bosporus.', fr: 'Le Parc d\'Emirgan est un parc historique de 47 hectares sur le Bosphore.', ar: 'حديقة أميرجان حديقة تاريخية بمساحة 47 هكتار على البوسفور.', ru: 'Парк Эмирган — 47 гектаров на берегу Босфора.' }, rating: 4.6, priceLevel: 0, popularityRank: 12, visitHours: { tr: '07:00 - 22:00', en: '7:00 AM - 10:00 PM', de: '07:00 - 22:00', fr: '07h00 - 22h00', ar: '07:00 - 22:00', ru: '07:00 - 22:00' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Otobüs 25E', en: 'Bus 25E', de: 'Bus 25E', fr: 'Bus 25E', ar: 'حافلة 25E', ru: 'Автобус 25E' }, tips: { tr: ['Nisan\'da lale festivali'], en: ['Tulip Festival in April'], de: ['Tulpenfest im April'], fr: ['Festival des tulipes en avril'], ar: ['مهرجان التوليب في أبريل'], ru: ['Фестиваль тюльпанов в апреле'] }, tags: ['nature', 'park', 'relaxation', 'photography'], emoji: '🌷', image: 'url(images/emirgan.jpg)' },

  { id: 'camlica', name: { tr: 'Çamlıca Tepesi', en: 'Çamlıca Hill', de: 'Çamlıca-Hügel', fr: 'Colline de Çamlıca', ar: 'تل تشامليجا', ru: 'Холм Чамлыджа' }, category: 'nature', district: 'Üsküdar', shortDesc: { tr: 'İstanbul\'un en yüksek tepesi.', en: 'Istanbul\'s highest hill.', de: 'Istanbuls höchster Hügel.', fr: 'La plus haute colline d\'Istanbul.', ar: 'أعلى تل في إسطنبول.', ru: 'Самый высокий холм Стамбула.' }, longDesc: { tr: 'Çamlıca Tepesi, Anadolu yakasının en yüksek noktasıdır. Boğaz ve Marmara manzarası sunar. Gün batımında nefes kesicidir.', en: 'Çamlıca Hill is the highest point on Istanbul\'s Asian side. Offers Bosphorus and Marmara Sea views. Breathtaking at sunset.', de: 'Der höchste Punkt auf Istanbuls asiatischer Seite.', fr: 'Le point le plus élevé du côté asiatique d\'Istanbul.', ar: 'أعلى نقطة في الجانب الآسيوي من إسطنبول.', ru: 'Самая высокая точка азиатской части Стамбула.' }, rating: 4.5, priceLevel: 0, popularityRank: 13, visitHours: { tr: '24 saat', en: '24 hours', de: '24 Stunden', fr: '24 heures', ar: '24 ساعة', ru: '24 часа' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Üsküdar\'dan otobüs', en: 'Bus from Üsküdar', de: 'Bus von Üsküdar', fr: 'Bus depuis Üsküdar', ar: 'حافلة من أوسكودار', ru: 'Автобус из Ускюдара' }, tips: { tr: ['Gün batımında gidin'], en: ['Go at sunset'], de: ['Zum Sonnenuntergang'], fr: ['Au coucher du soleil'], ar: ['اذهب عند الغروب'], ru: ['На закате'] }, tags: ['panorama', 'nature', 'photography'], emoji: '⛰️', image: 'url(images/camlica.jpg)' },

  { id: 'pierreloti', name: { tr: 'Pierre Loti Tepesi', en: 'Pierre Loti Hill', de: 'Pierre-Loti-Hügel', fr: 'Colline Pierre Loti', ar: 'تل بيير لوتي', ru: 'Холм Пьера Лоти' }, category: 'nature', district: 'Eyüp', shortDesc: { tr: 'Haliç manzaralı çay bahçesi ve teleferik.', en: 'Tea garden with Golden Horn views and cable car.', de: 'Teegarten mit Blick auf das Goldene Horn.', fr: 'Jardin de thé avec vue sur la Corne d\'Or.', ar: 'حديقة شاي مع إطلالة على القرن الذهبي.', ru: 'Чайный сад с видом на Золотой Рог.' }, longDesc: { tr: 'Pierre Loti Tepesi, Eyüp\'te Haliç\'e hakim konumdadır. Teleferik ile çıkılabilir. Geleneksel çay bahçesinde Türk çayı içmek unutulmazdır.', en: 'Pierre Loti Hill overlooks the Golden Horn in Eyüp. Accessible by cable car. Turkish tea in the traditional tea garden is unforgettable.', de: 'Der Pierre-Loti-Hügel überblickt das Goldene Horn. Per Seilbahn erreichbar.', fr: 'La colline Pierre Loti domine la Corne d\'Or. Accessible par téléphérique.', ar: 'يطل تل بيير لوتي على القرن الذهبي. يمكن الوصول بالتلفريك.', ru: 'Холм Пьера Лоти возвышается над Золотым Рогом. Доступен по канатной дороге.' }, rating: 4.5, priceLevel: 0, popularityRank: 14, visitHours: { tr: '08:00 - 00:00', en: '8:00 AM - 12:00 AM', de: '08:00 - 00:00', fr: '08h00 - 00h00', ar: '08:00 - 00:00', ru: '08:00 - 00:00' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Eyüp\'ten teleferik', en: 'Cable car from Eyüp', de: 'Seilbahn von Eyüp', fr: 'Téléphérique depuis Eyüp', ar: 'تلفريك من أيوب', ru: 'Канатная дорога от Эюп' }, tips: { tr: ['Teleferik ile çıkın'], en: ['Take cable car up'], de: ['Seilbahn nehmen'], fr: ['Prenez le téléphérique'], ar: ['اصعد بالتلفريك'], ru: ['На канатной дороге'] }, tags: ['panorama', 'café', 'relaxation'], emoji: '☕', image: 'url(images/pierreloti.jpg)' },

  { id: 'misircarsi', name: { tr: 'Mısır Çarşısı', en: 'Spice Bazaar', de: 'Gewürzbasar', fr: 'Bazar Égyptien', ar: 'سوق التوابل', ru: 'Египетский базар' }, category: 'shopping', district: 'Eminönü', shortDesc: { tr: '1660\'tan beri baharatların merkezi.', en: 'Center of spices since 1660.', de: 'Zentrum der Gewürze seit 1660.', fr: 'Centre des épices depuis 1660.', ar: 'مركز التوابل منذ 1660.', ru: 'Центр специй с 1660 года.' }, longDesc: { tr: 'Mısır Çarşısı, 1660 yılında inşa edilmiş 85 dükkânlı renkli çarşıdır. Baharatlar, lokumlar, kuruyemişler satılır. Beş duyuya hitap eder.', en: 'The Spice Bazaar, built in 1660, has 85 colorful shops selling spices, Turkish delight, and nuts. Appeals to all five senses.', de: 'Der Gewürzbasar von 1660 hat 85 Geschäfte mit Gewürzen, Lokum und Nüssen.', fr: 'Le Bazar Égyptien de 1660 a 85 boutiques d\'épices, loukoums et fruits secs.', ar: 'سوق التوابل من 1660 يضم 85 محلاً للتوابل والحلقوم والمكسرات.', ru: 'Египетский базар 1660 года — 85 лавок со специями, лукумом и орехами.' }, rating: 4.5, priceLevel: 1, popularityRank: 15, visitHours: { tr: '08:00 - 19:30 (Pazar kapalı)', en: '8:00 AM - 7:30 PM (Closed Sundays)', de: '08:00 - 19:30 (Sonntags geschlossen)', fr: '08h00 - 19h30 (Fermé dimanche)', ar: '08:00 - 19:30 (مغلق الأحد)', ru: '08:00 - 19:30 (закрыто по воскресеньям)' }, entranceFee: { tr: 'Ücretsiz', en: 'Free', de: 'Kostenlos', fr: 'Gratuit', ar: 'مجاني', ru: 'Бесплатно' }, transport: { tr: 'Tramvay T1 - Eminönü', en: 'Tram T1 - Eminönü', de: 'Tram T1 - Eminönü', fr: 'Tram T1 - Eminönü', ar: 'ترام T1 - أمينونو', ru: 'Трамвай T1 - Эминёню' }, tips: { tr: ['Lokum tadımı yapın'], en: ['Try Turkish delight samples'], de: ['Probieren Sie Lokum'], fr: ['Goûtez les loukoums'], ar: ['جرب عينات الحلقوم'], ru: ['Попробуйте лукум'] }, tags: ['shopping', 'spices', 'traditional'], emoji: '🌶️', image: 'url(images/misircarsi.jpg)' }
];

/* ══════════════════════════════════════
   FOOD PLACES — 4 Tier System
   ══════════════════════════════════════ */

const foodPlaces = [
  // ═══════ TIER 1: RESTORAN ═══════
  { id: 'ciya', name: 'Çiya Sofrası', tier: 1, district: 'Kadıköy', cuisine: { tr: 'Anadolu Mutfağı', en: 'Anatolian Cuisine', de: 'Anatolische Küche', fr: 'Cuisine Anatolienne', ar: 'المطبخ الأناضولي', ru: 'Анатолийская кухня' }, shortDesc: { tr: 'Anadolu\'nun unutulmuş lezzetleri.', en: 'Forgotten Anatolian flavors.', de: 'Vergessene anatolische Aromen.', fr: 'Saveurs anatoliennes oubliées.', ar: 'نكهات الأناضول المنسية.', ru: 'Забытые анатолийские вкусы.' }, longDesc: { tr: 'Çiya Sofrası, Kadıköy\'de Anadolu\'nun kaybolmaya yüz tutmuş lezzetlerini yaşatan benzersiz restoran. Netflix belgesellerine konu olmuştur.', en: 'Çiya Sofrası in Kadıköy keeps disappearing Anatolian flavors alive. Featured in Netflix documentaries.', de: 'Çiya Sofrası in Kadıköy bewahrt verschwindende anatolische Aromen.', fr: 'Çiya Sofrası à Kadıköy préserve les saveurs anatoliennes.', ar: 'مطعم فريد في كادي كوي يحافظ على نكهات الأناضول.', ru: 'Уникальный ресторан в Кадыкёе, сохраняющий анатолийские вкусы.' }, rating: 4.7, priceLevel: 2, signatureDishes: { tr: ['Kebap çeşitleri', 'Kuzu tandır'], en: ['Kebab varieties', 'Lamb tandoor'], de: ['Kebab-Variationen', 'Lamm-Tandur'], fr: ['Variétés de kebab', 'Agneau tandoor'], ar: ['أنواع الكباب', 'لحم ضأن تندور'], ru: ['Кебабы', 'Тандырная баранина'] }, visitHours: '11:00 - 22:00', tips: { tr: ['Öğle için erken gidin'], en: ['Go early for lunch'], de: ['Früh zum Mittagessen'], fr: ['Tôt pour le déjeuner'], ar: ['اذهب مبكراً للغداء'], ru: ['Рано на обед'] }, tags: ['traditional', 'local', 'culture'], emoji: '🍖', image: 'url(images/ciya.jpg)' },

  { id: 'sultanahmet_koftecisi', name: 'Tarihi Sultanahmet Köftecisi', tier: 1, district: 'Sultanahmet', cuisine: { tr: 'Köfte', en: 'Meatballs', de: 'Frikadellen', fr: 'Boulettes', ar: 'كفتة', ru: 'Кёфте' }, shortDesc: { tr: '1920\'den beri en meşhur köfteci.', en: 'Most famous meatball spot since 1920.', de: 'Berühmtester Köfte-Laden seit 1920.', fr: 'Le plus célèbre köfte depuis 1920.', ar: 'أشهر كفتة منذ 1920.', ru: 'Знаменитое кёфте с 1920.' }, longDesc: { tr: '1920\'den bu yana aynı tarif. Menüsü sadece köfte, piyaz ve tatlı.', en: 'Same recipe since 1920. Menu is only meatballs, bean salad and dessert.', de: 'Gleiches Rezept seit 1920.', fr: 'Même recette depuis 1920.', ar: 'نفس الوصفة منذ 1920.', ru: 'Тот же рецепт с 1920.' }, rating: 4.5, priceLevel: 2, signatureDishes: { tr: ['Köfte', 'Piyaz'], en: ['Meatballs', 'Bean salad'], de: ['Köfte', 'Bohnensalat'], fr: ['Boulettes', 'Salade'], ar: ['كفتة', 'سلطة فاصوليا'], ru: ['Кёфте', 'Салат'] }, visitHours: '10:30 - 22:00', tips: { tr: ['Kuyruk olabilir'], en: ['May have a queue'], de: ['Möglicherweise Schlange'], fr: ['Possible file d\'attente'], ar: ['قد يكون هناك طابور'], ru: ['Возможна очередь'] }, tags: ['traditional', 'history'], emoji: '🍖', image: 'url(images/sultanahmet_koftecisi.jpg)' },

  { id: 'mikla', name: 'Mikla', tier: 1, district: 'Beyoğlu', cuisine: { tr: 'Modern Türk', en: 'Modern Turkish', de: 'Moderne türkische Küche', fr: 'Cuisine turque moderne', ar: 'المطبخ التركي الحديث', ru: 'Современная турецкая' }, shortDesc: { tr: 'Ödüllü fine dining.', en: 'Award-winning fine dining.', de: 'Preisgekröntes Fine Dining.', fr: 'Fine dining primé.', ar: 'مطعم فاخر حائز على جوائز.', ru: 'Отмеченный наградами ресторан.' }, longDesc: { tr: 'Şef Mehmet Gürs\'ün Marmara Pera Hotel çatısındaki ödüllü restoranı. Teras manzarası muhteşemdir.', en: 'Chef Mehmet Gürs\' award-winning rooftop restaurant at Marmara Pera Hotel. Spectacular terrace views.', de: 'Preisgekröntes Dachrestaurant von Chefkoch Mehmet Gürs.', fr: 'Restaurant primé du chef Mehmet Gürs.', ar: 'مطعم الشيف محمد غورس الحائز على جوائز.', ru: 'Ресторан шефа Мехмета Гюрса.' }, rating: 4.6, priceLevel: 4, signatureDishes: { tr: ['Tadım menüsü', 'Kuzu'], en: ['Tasting menu', 'Lamb'], de: ['Degustationsmenü'], fr: ['Menu dégustation'], ar: ['قائمة تذوق'], ru: ['Дегустационное меню'] }, visitHours: '18:00 - 00:00', tips: { tr: ['Rezervasyon şart'], en: ['Reservation required'], de: ['Reservierung erforderlich'], fr: ['Réservation obligatoire'], ar: ['الحجز مطلوب'], ru: ['Бронирование обязательно'] }, tags: ['luxury', 'modern', 'panorama'], emoji: '🥂', image: 'url(images/mikla.jpg)' },

  { id: 'hamdi', name: 'Hamdi Restaurant', tier: 1, district: 'Eminönü', cuisine: { tr: 'Kebap', en: 'Kebab', de: 'Kebab', fr: 'Kebab', ar: 'كباب', ru: 'Кебаб' }, shortDesc: { tr: 'Haliç manzaralı kebapçı.', en: 'Kebab with Golden Horn views.', de: 'Kebab mit Blick auf das Goldene Horn.', fr: 'Kebab avec vue sur la Corne d\'Or.', ar: 'كباب مع إطلالة على القرن الذهبي.', ru: 'Кебаб с видом на Золотой Рог.' }, longDesc: { tr: 'Eminönü\'nde Haliç manzaralı kebap restoranı. Güneydoğu lezzetleri.', en: 'Kebab restaurant in Eminönü with Golden Horn views. Southeast flavors.', de: 'Kebab-Restaurant in Eminönü mit Blick auf das Goldene Horn.', fr: 'Restaurant de kebab à Eminönü avec vue.', ar: 'مطعم كباب في أمينونو مع إطلالة.', ru: 'Ресторан кебаба в Эминёню с видом.' }, rating: 4.5, priceLevel: 3, signatureDishes: { tr: ['Adana kebap', 'Urfa kebap'], en: ['Adana kebab', 'Urfa kebab'], de: ['Adana-Kebab'], fr: ['Kebab Adana'], ar: ['كباب أضنة'], ru: ['Кебаб Адана'] }, visitHours: '11:00 - 23:00', tips: { tr: ['Teras katını tercih edin'], en: ['Request terrace floor'], de: ['Terrasse wählen'], fr: ['Demandez la terrasse'], ar: ['اطلب الشرفة'], ru: ['Попросите террасу'] }, tags: ['traditional', 'panorama'], emoji: '🍢', image: 'url(images/hamdi.jpg)' },

  { id: 'balikci_sabahattin', name: 'Balıkçı Sabahattin', tier: 1, district: 'Sultanahmet', cuisine: { tr: 'Deniz Ürünleri', en: 'Seafood', de: 'Meeresfrüchte', fr: 'Fruits de mer', ar: 'مأكولات بحرية', ru: 'Морепродукты' }, shortDesc: { tr: 'Efsanevi balık restoranı.', en: 'Legendary fish restaurant.', de: 'Legendäres Fischrestaurant.', fr: 'Restaurant de poisson légendaire.', ar: 'مطعم أسماك أسطوري.', ru: 'Легендарный рыбный ресторан.' }, longDesc: { tr: 'Sultanahmet\'te tarihi evde balık restoranı. Meze çeşitleri ve taze balık.', en: 'Fish restaurant in a historic home in Sultanahmet. Great meze and fresh fish.', de: 'Fischrestaurant in historischem Haus in Sultanahmet.', fr: 'Restaurant de poisson dans une maison historique.', ar: 'مطعم أسماك في منزل تاريخي.', ru: 'Рыбный ресторан в историческом доме.' }, rating: 4.5, priceLevel: 3, signatureDishes: { tr: ['Levrek', 'Meze tabağı'], en: ['Sea bass', 'Meze platter'], de: ['Wolfsbarsch', 'Meze'], fr: ['Bar', 'Meze'], ar: ['قاروص', 'مزة'], ru: ['Сибас', 'Мезе'] }, visitHours: '12:00 - 23:00', tips: { tr: ['Meze tabağını alın'], en: ['Get the meze platter'], de: ['Bestellen Sie Meze'], fr: ['Commandez le meze'], ar: ['اطلب المزة'], ru: ['Закажите мезе'] }, tags: ['seafood', 'traditional'], emoji: '🐟', image: 'url(images/balikci_sabahattin.jpg)' },

  // ═══════ TIER 2: FAST FOOD ═══════
  { id: 'balik_ekmek', name: 'Eminönü Balık Ekmek', tier: 2, district: 'Eminönü', cuisine: { tr: 'Sokak Lezzeti', en: 'Street Food', de: 'Straßenessen', fr: 'Street Food', ar: 'طعام الشارع', ru: 'Уличная еда' }, shortDesc: { tr: 'İstanbul\'un simgesi balık ekmek.', en: 'Istanbul\'s iconic fish sandwich.', de: 'Istanbuls ikonisches Fischbrötchen.', fr: 'Sandwich de poisson iconique.', ar: 'ساندويتش السمك الأيقوني.', ru: 'Знаменитый рыбный сэндвич.' }, longDesc: { tr: 'Eminönü\'nde teknelerde taze pişirilen balık ekmek. Yanına turşu suyu iç.', en: 'Fresh fish sandwich grilled on boats in Eminönü. Pair with pickle juice.', de: 'Fischbrötchen auf Booten in Eminönü.', fr: 'Sandwich grillé sur bateaux à Eminönü.', ar: 'ساندويتش سمك مشوي على القوارب.', ru: 'Рыбный сэндвич на лодках в Эминёню.' }, rating: 4.4, priceLevel: 1, signatureDishes: { tr: ['Balık ekmek'], en: ['Fish sandwich'], de: ['Fischbrötchen'], fr: ['Sandwich poisson'], ar: ['ساندويتش سمك'], ru: ['Рыбный сэндвич'] }, visitHours: '11:00 - 21:00', tips: { tr: ['Turşu suyu alın'], en: ['Get pickle juice'], de: ['Gurkenwasser dazu'], fr: ['Prenez du jus de cornichon'], ar: ['خذ ماء المخلل'], ru: ['Возьмите рассол'] }, tags: ['street', 'seafood'], emoji: '🐟', image: 'url(images/balik_ekmek.jpg)' },

  { id: 'kizilkayalar', name: 'Kızılkayalar', tier: 2, district: 'Taksim', cuisine: { tr: 'Islak Hamburger', en: 'Wet Burger', de: 'Nasser Burger', fr: 'Burger humide', ar: 'برغر رطب', ru: 'Мокрый бургер' }, shortDesc: { tr: 'Efsanevi ıslak hamburger.', en: 'Legendary wet burger.', de: 'Legendärer nasser Burger.', fr: 'Légendaire burger humide.', ar: 'البرغر الرطب الأسطوري.', ru: 'Легендарный мокрый бургер.' }, longDesc: { tr: 'İstanbul\'un benzersiz sokak lezzeti. Gece gezmelerinin vazgeçilmezi.', en: 'Istanbul\'s unique street food. A must during late-night outings.', de: 'Einzigartiges Straßenessen Istanbuls.', fr: 'Street food unique d\'Istanbul.', ar: 'طعام شارع فريد في إسطنبول.', ru: 'Уникальная уличная еда Стамбула.' }, rating: 4.2, priceLevel: 1, signatureDishes: { tr: ['Islak hamburger'], en: ['Wet burger'], de: ['Nasser Burger'], fr: ['Burger humide'], ar: ['برغر رطب'], ru: ['Мокрый бургер'] }, visitHours: '24 saat', tips: { tr: ['Gece daha lezzetli!'], en: ['Tastier at night!'], de: ['Nachts besser!'], fr: ['Meilleur la nuit !'], ar: ['ألذ في الليل!'], ru: ['Вкуснее ночью!'] }, tags: ['street', 'nightlife'], emoji: '🍔', image: 'url(images/kizilkayalar.jpg)' },

  { id: 'durumzade', name: 'Dürümzade', tier: 2, district: 'Beyoğlu', cuisine: { tr: 'Dürüm', en: 'Wrap', de: 'Dürüm', fr: 'Dürüm', ar: 'دوروم', ru: 'Дюрюм' }, shortDesc: { tr: 'İstanbul\'un en iyi dürümcüsü.', en: 'Istanbul\'s best wrap spot.', de: 'Bester Dürüm Istanbuls.', fr: 'Meilleur dürüm d\'Istanbul.', ar: 'أفضل دوروم في إسطنبول.', ru: 'Лучший дюрюм Стамбула.' }, longDesc: { tr: 'Beyoğlu\'nda küçük ama efsanevi dürümcü. Michelin rehberinde önerilmiştir.', en: 'Small but legendary wrap shop in Beyoğlu. Michelin recommended.', de: 'Klein aber legendär in Beyoğlu. Michelin empfohlen.', fr: 'Petit mais légendaire à Beyoğlu. Recommandé Michelin.', ar: 'صغير لكن أسطوري في بيوغلو. موصى من ميشلان.', ru: 'Маленькое, но легендарное место в Бейоглу.' }, rating: 4.5, priceLevel: 1, signatureDishes: { tr: ['Adana dürüm', 'Beyti'], en: ['Adana wrap', 'Beyti'], de: ['Adana-Dürüm'], fr: ['Dürüm Adana'], ar: ['دوروم أضنة'], ru: ['Дюрюм Адана'] }, visitHours: '11:00 - 02:00', tips: { tr: ['Acılı isteyin'], en: ['Ask for spicy'], de: ['Scharf bestellen'], fr: ['Demandez épicé'], ar: ['اطلبه حاراً'], ru: ['Попросите острый'] }, tags: ['street', 'traditional'], emoji: '🌯', image: 'url(images/durumzade.jpg)' },

  { id: 'karadeniz_pide', name: 'Tarihi Karadeniz Pidecisi', tier: 2, district: 'Fatih', cuisine: { tr: 'Pide', en: 'Turkish Pizza', de: 'Pide', fr: 'Pide', ar: 'بيدا', ru: 'Пиде' }, shortDesc: { tr: 'Karadeniz usulü pideler.', en: 'Black Sea style pide.', de: 'Schwarzmeer-Pide.', fr: 'Pide Mer Noire.', ar: 'بيدا بأسلوب البحر الأسود.', ru: 'Пиде черноморского стиля.' }, longDesc: { tr: 'Fatih\'te geleneksel Karadeniz pideleri. Kaşarlı ve kıymalı favoriler.', en: 'Traditional Black Sea pides in Fatih. Cheese and minced meat are favorites.', de: 'Traditionelle Schwarzmeer-Pide in Fatih.', fr: 'Pide traditionnels de la Mer Noire à Fatih.', ar: 'بيدا تقليدي من البحر الأسود في فاتح.', ru: 'Традиционные черноморские пиде в Фатихе.' }, rating: 4.4, priceLevel: 2, signatureDishes: { tr: ['Kaşarlı pide', 'Kıymalı pide'], en: ['Cheese pide', 'Meat pide'], de: ['Käse-Pide', 'Fleisch-Pide'], fr: ['Pide fromage', 'Pide viande'], ar: ['بيدا جبن', 'بيدا لحم'], ru: ['Пиде с сыром', 'Пиде с мясом'] }, visitHours: '10:00 - 23:00', tips: { tr: ['Kuşbaşılı deneyin'], en: ['Try cubed meat'], de: ['Mit Fleischwürfeln'], fr: ['Essayez la viande en cubes'], ar: ['جرب اللحم المكعب'], ru: ['С кусочками мяса'] }, tags: ['traditional'], emoji: '🫓', image: 'url(images/karadeniz_pide.jpg)' },

  { id: 'borsam', name: 'Borsam Taşfırın', tier: 2, district: 'Kadıköy', cuisine: { tr: 'Lahmacun', en: 'Lahmacun', de: 'Lahmacun', fr: 'Lahmacun', ar: 'لحم بعجين', ru: 'Лахмаджун' }, shortDesc: { tr: 'Kadıköy\'ün en iyi lahmacunu.', en: 'Kadıköy\'s best lahmacun.', de: 'Bester Lahmacun in Kadıköy.', fr: 'Meilleur lahmacun de Kadıköy.', ar: 'أفضل لحم بعجين في كادي كوي.', ru: 'Лучший лахмаджун Кадыкёя.' }, longDesc: { tr: 'Taş fırında pişirilen lahmacun ve pideler. İnce hamuru ile ünlü.', en: 'Stone-oven lahmacun and pides. Famous for thin dough.', de: 'Steinofen-Lahmacun mit dünnem Teig.', fr: 'Lahmacun au four à pierre.', ar: 'لحم بعجين من الفرن الحجري.', ru: 'Лахмаджун из каменной печи.' }, rating: 4.5, priceLevel: 1, signatureDishes: { tr: ['Lahmacun', 'Pide'], en: ['Lahmacun', 'Pide'], de: ['Lahmacun'], fr: ['Lahmacun'], ar: ['لحم بعجين'], ru: ['Лахмаджун'] }, visitHours: '09:00 - 23:00', tips: { tr: ['Limon sıkın'], en: ['Squeeze lemon'], de: ['Zitrone drücken'], fr: ['Pressez du citron'], ar: ['اعصر ليموناً'], ru: ['Выжмите лимон'] }, tags: ['street', 'traditional'], emoji: '🫓', image: 'url(images/borsam.jpg)' },

  // ═══════ TIER 3: KAFE ═══════
  { id: 'mandabatmaz', name: 'Mandabatmaz', tier: 3, district: 'Beyoğlu', cuisine: { tr: 'Türk Kahvesi', en: 'Turkish Coffee', de: 'Türkischer Kaffee', fr: 'Café turc', ar: 'القهوة التركية', ru: 'Турецкий кофе' }, shortDesc: { tr: 'İstanbul\'un en iyi Türk kahvesi.', en: 'Istanbul\'s best Turkish coffee.', de: 'Bester türkischer Kaffee Istanbuls.', fr: 'Meilleur café turc d\'Istanbul.', ar: 'أفضل قهوة تركية في إسطنبول.', ru: 'Лучший турецкий кофе Стамбула.' }, longDesc: { tr: 'Küçücük mekanda İstanbul\'un en yoğun Türk kahvesi. İsim "manda bile batmaz" ifadesinden gelir.', en: 'In a tiny spot, Istanbul\'s thickest Turkish coffee. Name means "even a buffalo won\'t sink."', de: 'In einem winzigen Laden Istanbuls dickster Kaffee.', fr: 'Le café turc le plus épais dans un minuscule endroit.', ar: 'أغلظ قهوة تركية في مكان صغير جداً.', ru: 'Самый густой кофе в крошечном месте.' }, rating: 4.6, priceLevel: 1, signatureDishes: { tr: ['Türk kahvesi'], en: ['Turkish coffee'], de: ['Türkischer Kaffee'], fr: ['Café turc'], ar: ['قهوة تركية'], ru: ['Турецкий кофе'] }, visitHours: '09:00 - 00:00', tips: { tr: ['Orta şekerli deneyin'], en: ['Try medium sweet'], de: ['Mittelsüß probieren'], fr: ['Essayez moyennement sucré'], ar: ['جرب متوسط الحلاوة'], ru: ['Средний сахар'] }, tags: ['traditional', 'café'], emoji: '☕', image: 'url(images/mandabatmaz.jpg)' },

  { id: 'kronotrop', name: 'Kronotrop', tier: 3, district: 'Galata', cuisine: { tr: 'Specialty Coffee', en: 'Specialty Coffee', de: 'Specialty Coffee', fr: 'Café de spécialité', ar: 'قهوة مختصة', ru: 'Спешиалти кофе' }, shortDesc: { tr: 'Üçüncü dalga kahveciliğin öncüsü.', en: 'Third wave coffee pioneer.', de: 'Third-Wave-Kaffee-Pionier.', fr: 'Pionnier du café troisième vague.', ar: 'رائد القهوة المختصة.', ru: 'Пионер третьей волны кофе.' }, longDesc: { tr: 'Galata\'da üçüncü dalga kahve öncüsü. Kendi kavurduğu çekirdekler.', en: 'Third wave coffee pioneer in Galata. They roast their own beans.', de: 'Third-Wave-Pionier in Galata.', fr: 'Pionnier troisième vague à Galata.', ar: 'رائد في غلطة يحمص حبوبه.', ru: 'Пионер в Галате, обжаривают свои зёрна.' }, rating: 4.5, priceLevel: 2, signatureDishes: { tr: ['Pour over', 'Cold brew'], en: ['Pour over', 'Cold brew'], de: ['Pour over', 'Cold brew'], fr: ['Pour over', 'Cold brew'], ar: ['بور أوفر', 'كولد برو'], ru: ['Пуровер', 'Колд брю'] }, visitHours: '08:00 - 22:00', tips: { tr: ['V60 deneyin'], en: ['Try V60'], de: ['V60 probieren'], fr: ['Essayez V60'], ar: ['جرب V60'], ru: ['Попробуйте V60'] }, tags: ['modern', 'café'], emoji: '☕', image: 'url(images/kronotrop.jpg)' },

  { id: 'pierre_loti_kafe', name: 'Pierre Loti Kahvesi', tier: 3, district: 'Eyüp', cuisine: { tr: 'Çay & Kahve', en: 'Tea & Coffee', de: 'Tee & Kaffee', fr: 'Thé & Café', ar: 'شاي وقهوة', ru: 'Чай и кофе' }, shortDesc: { tr: 'Haliç manzaralı çay bahçesi.', en: 'Tea garden with Golden Horn views.', de: 'Teegarten mit Goldenem Horn.', fr: 'Jardin de thé avec vue.', ar: 'حديقة شاي مع إطلالة.', ru: 'Чайный сад с видом.' }, longDesc: { tr: 'Pierre Loti Tepesi\'ndeki tarihi çay bahçesi. Haliç manzarası eşliğinde çay içmek unutulmaz.', en: 'Historic tea garden on Pierre Loti Hill. Drinking tea with Golden Horn views is unforgettable.', de: 'Historischer Teegarten auf dem Pierre-Loti-Hügel.', fr: 'Jardin de thé historique sur la colline Pierre Loti.', ar: 'حديقة شاي تاريخية على تل بيير لوتي.', ru: 'Исторический чайный сад на холме Пьера Лоти.' }, rating: 4.3, priceLevel: 1, signatureDishes: { tr: ['Türk çayı', 'Türk kahvesi'], en: ['Turkish tea', 'Turkish coffee'], de: ['Türkischer Tee'], fr: ['Thé turc'], ar: ['شاي تركي'], ru: ['Турецкий чай'] }, visitHours: '08:00 - 00:00', tips: { tr: ['Teleferik ile çıkın'], en: ['Take cable car'], de: ['Seilbahn nehmen'], fr: ['Prenez le téléphérique'], ar: ['اصعد بالتلفريك'], ru: ['На канатной дороге'] }, tags: ['traditional', 'panorama', 'relaxation'], emoji: '🫖', image: 'url(images/pierre_loti_kafe.jpg)' },

  { id: 'fazil_bey', name: 'Fazıl Bey', tier: 3, district: 'Kadıköy', cuisine: { tr: 'Türk Kahvesi', en: 'Turkish Coffee', de: 'Türkischer Kaffee', fr: 'Café turc', ar: 'القهوة التركية', ru: 'Турецкий кофе' }, shortDesc: { tr: '1923\'ten beri kahve kültürü.', en: 'Coffee culture since 1923.', de: 'Kaffeekultur seit 1923.', fr: 'Culture du café depuis 1923.', ar: 'ثقافة القهوة منذ 1923.', ru: 'Кофейная культура с 1923.' }, longDesc: { tr: 'Kadıköy çarşısında 1923\'ten beri tarihi kahveci. Dibek kahvesi ile ünlü.', en: 'Historic coffee shop in Kadıköy market since 1923. Famous for dibek coffee.', de: 'Historisches Kaffeehaus seit 1923 in Kadıköy.', fr: 'Café historique depuis 1923 à Kadıköy.', ar: 'مقهى تاريخي في كادي كوي منذ 1923.', ru: 'Историческая кофейня с 1923 года.' }, rating: 4.4, priceLevel: 1, signatureDishes: { tr: ['Türk kahvesi', 'Dibek'], en: ['Turkish coffee', 'Dibek'], de: ['Türkischer Kaffee', 'Dibek'], fr: ['Café turc', 'Dibek'], ar: ['قهوة تركية', 'ديبك'], ru: ['Турецкий кофе', 'Дибек'] }, visitHours: '07:00 - 23:00', tips: { tr: ['Damla sakızlı deneyin'], en: ['Try mastic coffee'], de: ['Mastix-Kaffee probieren'], fr: ['Essayez le café au mastic'], ar: ['جرب قهوة المصطكى'], ru: ['С мастикой'] }, tags: ['traditional', 'history', 'café'], emoji: '☕', image: 'url(images/fazil_bey.jpg)' },

  // ═══════ TIER 4: TATLICI ═══════
  { id: 'gulluoglu', name: 'Karaköy Güllüoğlu', tier: 4, district: 'Karaköy', cuisine: { tr: 'Baklava', en: 'Baklava', de: 'Baklava', fr: 'Baklava', ar: 'بقلاوة', ru: 'Баклава' }, shortDesc: { tr: 'Türkiye\'nin en ünlü baklavacısı.', en: 'Turkey\'s most famous baklava maker.', de: 'Berühmtester Baklava-Hersteller.', fr: 'Plus célèbre baklava de Turquie.', ar: 'أشهر صانع بقلاوة في تركيا.', ru: 'Самая знаменитая баклава Турции.' }, longDesc: { tr: 'Karaköy\'de 1949\'dan beri. Fıstıklı baklava ve havuç dilim en popüler.', en: 'In Karaköy since 1949. Pistachio baklava and carrot slice most popular.', de: 'In Karaköy seit 1949. Pistazien-Baklava am beliebtesten.', fr: 'À Karaköy depuis 1949. Baklava pistache la plus populaire.', ar: 'في كاراكوي منذ 1949. بقلاوة الفستق الأكثر شهرة.', ru: 'В Каракёе с 1949. Баклава с фисташками популярнее всего.' }, rating: 4.7, priceLevel: 2, signatureDishes: { tr: ['Fıstıklı baklava', 'Havuç dilim', 'Şöbiyet'], en: ['Pistachio baklava', 'Carrot slice', 'Şöbiyet'], de: ['Pistazien-Baklava'], fr: ['Baklava pistache'], ar: ['بقلاوة فستق'], ru: ['Баклава с фисташками'] }, visitHours: '07:00 - 23:30', tips: { tr: ['Kaymak ile deneyin'], en: ['Try with clotted cream'], de: ['Mit Sahne probieren'], fr: ['Essayez avec de la crème'], ar: ['جربها مع القشطة'], ru: ['С каймаком'] }, tags: ['traditional', 'dessert'], emoji: '🍯', image: 'url(images/gulluoglu.jpg)' },

  { id: 'hafiz_mustafa', name: 'Hafız Mustafa 1864', tier: 4, district: 'Sultanahmet', cuisine: { tr: 'Osmanlı Tatlıları', en: 'Ottoman Sweets', de: 'Osmanische Süßigkeiten', fr: 'Douceurs ottomanes', ar: 'حلويات عثمانية', ru: 'Османские сладости' }, shortDesc: { tr: '1864\'ten beri Osmanlı tatlıları.', en: 'Ottoman sweets since 1864.', de: 'Osmanische Süßigkeiten seit 1864.', fr: 'Douceurs ottomanes depuis 1864.', ar: 'حلويات عثمانية منذ 1864.', ru: 'Османские сладости с 1864.' }, longDesc: { tr: '1864\'te kurulan İstanbul\'un en eski tatlıcılarından. Baklava, lokum, künefe meşhur.', en: 'Founded 1864, one of Istanbul\'s oldest confectioners. Famous for baklava, Turkish delight, künefe.', de: 'Gegründet 1864, einer der ältesten Konditoren.', fr: 'Fondé en 1864, l\'un des plus anciens confiseurs.', ar: 'أسس 1864، من أقدم صانعي الحلويات.', ru: 'Основана в 1864, одна из старейших кондитерских.' }, rating: 4.6, priceLevel: 2, signatureDishes: { tr: ['Baklava', 'Lokum', 'Künefe'], en: ['Baklava', 'Turkish delight', 'Künefe'], de: ['Baklava', 'Lokum', 'Künefe'], fr: ['Baklava', 'Loukoum', 'Künefe'], ar: ['بقلاوة', 'حلقوم', 'كنافة'], ru: ['Баклава', 'Лукум', 'Кюнефе'] }, visitHours: '07:00 - 01:00', tips: { tr: ['Osmanlı macununu deneyin'], en: ['Try Ottoman paste'], de: ['Osmanische Paste probieren'], fr: ['Essayez la pâte ottomane'], ar: ['جرب المعجون العثماني'], ru: ['Османская паста'] }, tags: ['traditional', 'dessert', 'history'], emoji: '🍬', image: 'url(images/hafiz_mustafa.jpg)' },

  { id: 'haci_bekir', name: 'Ali Muhiddin Hacı Bekir', tier: 4, district: 'Eminönü', cuisine: { tr: 'Lokum', en: 'Turkish Delight', de: 'Lokum', fr: 'Loukoum', ar: 'حلقوم', ru: 'Лукум' }, shortDesc: { tr: '1777\'den beri lokumun mucidi.', en: 'Inventor of Turkish delight since 1777.', de: 'Erfinder des Lokum seit 1777.', fr: 'Inventeur du loukoum depuis 1777.', ar: 'مخترع الحلقوم منذ 1777.', ru: 'Изобретатель лукума с 1777.' }, longDesc: { tr: '1777\'de kurulan lokumun mucidi. Geleneksel el yapımı üretim devam ediyor.', en: 'Founded 1777, inventor of Turkish delight. Traditional handmade production continues.', de: 'Gegründet 1777, Erfinder des Lokum.', fr: 'Fondé en 1777, inventeur du loukoum.', ar: 'أُسس 1777، مخترع الحلقوم.', ru: 'Основан в 1777, изобретатель лукума.' }, rating: 4.5, priceLevel: 2, signatureDishes: { tr: ['Lokum', 'Akide şekeri'], en: ['Turkish delight', 'Rock candy'], de: ['Lokum', 'Bonbons'], fr: ['Loukoum', 'Bonbons'], ar: ['حلقوم', 'أكيدا'], ru: ['Лукум', 'Леденцы'] }, visitHours: '08:30 - 20:00', tips: { tr: ['Gül lokumu deneyin'], en: ['Try rose delight'], de: ['Rosen-Lokum probieren'], fr: ['Essayez le loukoum à la rose'], ar: ['جرب حلقوم الورد'], ru: ['Розовый лукум'] }, tags: ['traditional', 'dessert', 'history'], emoji: '🍬', image: 'url(images/haci_bekir.jpg)' },

  { id: 'saray_muhallebicisi', name: 'Saray Muhallebicisi', tier: 4, district: 'Beyoğlu', cuisine: { tr: 'Sütlü Tatlılar', en: 'Milk Desserts', de: 'Milchdesserts', fr: 'Desserts lactés', ar: 'حلويات حليبية', ru: 'Молочные десерты' }, shortDesc: { tr: 'İstiklal\'in muhallebicisi.', en: 'Istiklal\'s pudding shop.', de: 'Istiklals Puddingladen.', fr: 'Pâtisserie d\'Istiklal.', ar: 'محل المهلبية في الاستقلال.', ru: 'Кондитерская на Истикляль.' }, longDesc: { tr: 'İstiklal Caddesi\'nde sütlü tatlılarıyla meşhur. Kazandibi ve profiterol en popüler.', en: 'Famous for milk desserts on Istiklal. Kazandibi and profiterole most popular.', de: 'Berühmt für Milchdesserts auf der Istiklal.', fr: 'Célèbre pour desserts lactés sur Istiklal.', ar: 'مشهور بالحلويات الحليبية في الاستقلال.', ru: 'Знаменита молочными десертами на Истикляль.' }, rating: 4.4, priceLevel: 1, signatureDishes: { tr: ['Kazandibi', 'Profiterol', 'Sütlaç'], en: ['Kazandibi', 'Profiterole', 'Rice pudding'], de: ['Kazandibi', 'Profiterol'], fr: ['Kazandibi', 'Profiterole'], ar: ['كازانديبي', 'بروفيترول'], ru: ['Казандиби', 'Профитроли'] }, visitHours: '06:00 - 02:00', tips: { tr: ['Kazandibi mutlaka'], en: ['Must try kazandibi'], de: ['Kazandibi probieren'], fr: ['Essayez kazandibi'], ar: ['جرب كازانديبي'], ru: ['Казандиби обязательно'] }, tags: ['traditional', 'dessert'], emoji: '🍮', image: 'url(images/saray_muhallebicisi.jpg)' },

  { id: 'mado', name: 'Mado', tier: 4, district: 'Çeşitli', cuisine: { tr: 'Dondurma', en: 'Ice Cream', de: 'Eiscreme', fr: 'Glace', ar: 'آيس كريم', ru: 'Мороженое' }, shortDesc: { tr: 'Maraş dondurmasının markası.', en: 'Famous Maraş ice cream brand.', de: 'Berühmte Maraş-Eiscreme.', fr: 'Célèbre glace Maraş.', ar: 'ماركة آيس كريم مرعش الشهيرة.', ru: 'Знаменитое мороженое Мараш.' }, longDesc: { tr: 'Kahramanmaraş usulü dövme dondurma markası. Salep ve keçi sütü ile yapılır. Uzayan dondurma benzersizdir.', en: 'Kahramanmaraş-style beaten ice cream brand. Made with salep and goat\'s milk. Stretchy ice cream is unique.', de: 'Maraş-Eiscreme aus Salep und Ziegenmilch.', fr: 'Glace Maraş à base de salep et lait de chèvre.', ar: 'آيس كريم مرعش من السحلب وحليب الماعز.', ru: 'Мороженое Мараш из салепа и козьего молока.' }, rating: 4.3, priceLevel: 2, signatureDishes: { tr: ['Maraş dondurması', 'Künefe'], en: ['Maraş ice cream', 'Künefe'], de: ['Maraş-Eiscreme'], fr: ['Glace Maraş'], ar: ['آيس كريم مرعش'], ru: ['Мороженое Мараш'] }, visitHours: '09:00 - 00:00', tips: { tr: ['Sade ve fıstıklı karışık'], en: ['Try plain and pistachio mix'], de: ['Natur und Pistazie mischen'], fr: ['Mélange nature et pistache'], ar: ['جرب خليط السادة والفستق'], ru: ['Натуральное с фисташкой'] }, tags: ['dessert', 'traditional'], emoji: '🍦', image: 'url(images/mado.jpg)' }
];
