/* ═══════════════════════════════════════
   Languages — 6 Language Translation Data
   ═══════════════════════════════════════ */

const langMeta = {
    tr: { flag: '🇹🇷', name: 'Türkçe', code: 'TR', dir: 'ltr' },
    en: { flag: '🇬🇧', name: 'English', code: 'EN', dir: 'ltr' },
    de: { flag: '🇩🇪', name: 'Deutsch', code: 'DE', dir: 'ltr' },
    fr: { flag: '🇫🇷', name: 'Français', code: 'FR', dir: 'ltr' },
    ar: { flag: '🇸🇦', name: 'العربية', code: 'AR', dir: 'rtl' },
    ru: { flag: '🇷🇺', name: 'Русский', code: 'RU', dir: 'ltr' }
};

const translations = {

/* ╔═══════════════════════════╗
   ║        TÜRKÇE (TR)        ║
   ╚═══════════════════════════╝ */
tr: {
    // Welcome
    welcome_badge: 'KİŞİSEL GEZİ REHBERİ',
    welcome_title_1: "İstanbul'u",
    welcome_title_2: 'Keşfedin',
    welcome_desc: '15 soruluk testimizi çözün, size özel hazırlanmış gezi rehberinizi alın. En popüler mekanlar, restoranlar, kafeler ve daha fazlası!',
    welcome_f1: '15 Soru Test',
    welcome_f2: 'Kişisel Rehber',
    welcome_f3: 'Yemek Rehberi',
    welcome_f4: 'Popüler Yerler',
    welcome_lang_prompt: 'Dilinizi seçin',
    welcome_start: 'Teste Başla',

    // Quiz
    quiz_home: 'Ana Sayfa',
    quiz_prev: 'Önceki',
    quiz_next: 'Sonraki',
    quiz_finish: 'Testi Bitir',

    // Q1
    q1_text: 'Tatilde en çok ne yapmaktan hoşlanırsınız?',
    q1_a: 'Tarihi yerleri gezmek',
    q1_b: 'Yerel lezzetleri tatmak',
    q1_c: 'Doğada vakit geçirmek',
    q1_d: 'Alışveriş yapmak',
    // Q2
    q2_text: 'Yemek tercihiniz hangisi?',
    q2_a: 'Geleneksel Türk mutfağı',
    q2_b: 'Sokak lezzetleri',
    q2_c: 'Deniz ürünleri',
    q2_d: 'Uluslararası mutfak',
    // Q3
    q3_text: 'Bütçe seviyeniz nedir?',
    q3_a: 'Ekonomik',
    q3_b: 'Orta',
    q3_c: 'Konforlu',
    q3_d: 'Lüks',
    // Q4
    q4_text: 'Günde ne kadar yürüyebilirsiniz?',
    q4_a: 'Çok az, mola severim',
    q4_b: 'Birkaç saat yürüyebilirim',
    q4_c: 'Uzun yürüyüşleri severim',
    q4_d: 'Tüm gün yürüyebilirim',
    // Q5
    q5_text: 'Kiminle seyahat ediyorsunuz?',
    q5_a: 'Yalnız',
    q5_b: 'Eşim/partnerimle',
    q5_c: 'Ailemle',
    q5_d: 'Arkadaş grubumla',
    // Q6
    q6_text: 'Günün hangi zamanını tercih edersiniz?',
    q6_a: 'Sabah erken saatler',
    q6_b: 'Öğle saatleri',
    q6_c: 'Akşam üzeri',
    q6_d: 'Gece hayatı',
    // Q7
    q7_text: 'Fotoğraf çekmek sizin için ne kadar önemli?',
    q7_a: 'Çok önemli, her anı çekerim',
    q7_b: 'Özel yerlerde çekerim',
    q7_c: 'Nadiren çekerim',
    q7_d: 'Hiç çekmem, anın tadını çıkarırım',
    // Q8
    q8_text: 'Tarih ve mimari ne kadar ilginizi çeker?',
    q8_a: 'Çok ilgimi çeker, detayları severim',
    q8_b: 'Önemli yerleri görmek isterim',
    q8_c: 'Biraz ilgimi çeker',
    q8_d: 'Pek ilgimi çekmez',
    // Q9
    q9_text: 'Yerel mutfağı ne kadar denemek istersiniz?',
    q9_a: 'Her şeyi denemek isterim',
    q9_b: 'Popüler yemekleri denerim',
    q9_c: 'Tanıdık tatlar tercih ederim',
    q9_d: 'Kendi yemek alışkanlıklarıma bağlıyım',
    // Q10
    q10_text: 'Deniz ve Boğaz aktiviteleri sizi cezbeder mi?',
    q10_a: 'Kesinlikle, çok severim',
    q10_b: 'Evet, güzel olur',
    q10_c: 'Fark etmez',
    q10_d: 'Hayır, karayı tercih ederim',
    // Q11
    q11_text: 'Alışveriş yapmayı sever misiniz?',
    q11_a: 'Çok severim, her yere uğrarım',
    q11_b: 'Hediyelik eşya alırım',
    q11_c: 'Sadece ihtiyaç olursa',
    q11_d: 'Pek alışveriş yapmam',
    // Q12
    q12_text: "Kaç gün İstanbul'da kalacaksınız?",
    q12_a: '1-2 gün',
    q12_b: '3-4 gün',
    q12_c: '5-7 gün',
    q12_d: 'Bir haftadan fazla',
    // Q13
    q13_text: 'Mekan tercihiniz nedir?',
    q13_a: 'Kalabalık ve canlı yerler',
    q13_b: 'Popüler ama dengeli',
    q13_c: 'Sakin ve huzurlu',
    q13_d: 'Keşfedilmemiş gizli köşeler',
    // Q14
    q14_text: 'Sanat ve müzeler ilginizi çeker mi?',
    q14_a: 'Çok, müze turları yaparım',
    q14_b: 'Önemli müzeleri gezerim',
    q14_c: 'Bazen ilgimi çeker',
    q14_d: 'Pek ilgimi çekmez',
    // Q15
    q15_text: 'Seyahat tarzınızı en iyi hangisi tanımlar?',
    q15_a: 'Planlı ve organize',
    q15_b: 'Karışık, hem plan hem spontan',
    q15_c: 'Tamamen spontan ve macera dolu',
    q15_d: 'Rahat ve stressiz',

    // Result
    result_badge: 'SENİN PROFİLİN',
    result_see_guide: 'Rehberimi Gör',
    result_retake: 'Testi Tekrar Çöz',

    // Profiles
    profile_historian_name: 'Tarih Aşığı',
    profile_historian_desc: "Tarihi mekanları ve kültürel zenginlikleri keşfetmeyi seviyorsunuz. İstanbul'un binlerce yıllık hikayesi sizi bekliyor!",
    profile_foodie_name: 'Gurme Gezgin',
    profile_foodie_desc: "Damak tadınız çok gelişmiş! İstanbul'un eşsiz mutfağını keşfetmek sizin için en büyük macera.",
    profile_nature_name: 'Doğa Tutkunu',
    profile_nature_desc: "Huzurlu parklar, deniz manzaraları ve yeşil alanlar tam size göre. İstanbul'un doğal güzellikleri sizi büyüleyecek!",
    profile_shopper_name: 'Alışveriş Tutkunu',
    profile_shopper_desc: "Çarşılar, butikler ve mağazalar sizin doğal yaşam alanınız. İstanbul alışveriş cenneti sizin için!",
    profile_explorer_name: 'Kaşif Ruh',
    profile_explorer_desc: "Bilinmeyen sokakları keşfetmek, gizli köşeleri bulmak ve macera yaşamak sizin tarzınız!",

    // Categories
    cat_history: 'Tarih & Kültür',
    cat_food: 'Gastronomi',
    cat_nature: 'Doğa & Huzur',
    cat_shopping: 'Alışveriş & Eğlence',
    cat_adventure: 'Keşif & Macera',

    // Guide
    guide_title: 'Gezi Rehberiniz',
    guide_subtitle_prefix: 'Profilinize göre öneriler:',
    tab_recommended: 'Önerilen',
    tab_popular: 'En Popüler',
    tab_food: 'Yemek',
    tab_all: 'Tümü',
    food_all: 'Tümü',
    food_restaurant: 'Restoran',
    food_fastfood: 'Fast Food',
    food_cafe: 'Kafe',
    food_dessert: 'Tatlıcı',

    // Detail
    detail_back: 'Geri',
    detail_rating: 'Puan',
    detail_price: 'Fiyat',
    detail_popularity: 'Popülerlik',
    detail_about: 'Hakkında',
    detail_info: 'Pratik Bilgiler',
    detail_signature: 'Öne Çıkan Lezzetler',
    detail_tips: 'İpuçları',
    detail_nearby: 'Yakın Mekanlar',
    detail_hours: 'Ziyaret Saatleri',
    detail_entrance: 'Giriş Ücreti',
    detail_transport: 'Ulaşım',
    detail_free: 'Ücretsiz',
    detail_very_popular: 'Çok Popüler',
    detail_popular: 'Popüler',
    detail_moderate: 'Orta',

    // Footer
    footer_text: 'Tüm hakları saklıdır'
},

/* ╔═══════════════════════════╗
   ║       ENGLISH (EN)        ║
   ╚═══════════════════════════╝ */
en: {
    welcome_badge: 'PERSONAL TRAVEL GUIDE',
    welcome_title_1: 'Discover',
    welcome_title_2: 'Istanbul',
    welcome_desc: 'Take our 15-question quiz and get your personalized travel guide. Top attractions, restaurants, cafes and more!',
    welcome_f1: '15 Question Quiz',
    welcome_f2: 'Personal Guide',
    welcome_f3: 'Food Guide',
    welcome_f4: 'Popular Places',
    welcome_lang_prompt: 'Choose your language',
    welcome_start: 'Start Quiz',

    quiz_home: 'Home',
    quiz_prev: 'Previous',
    quiz_next: 'Next',
    quiz_finish: 'Finish Quiz',

    q1_text: 'What do you enjoy most on vacation?',
    q1_a: 'Visiting historical sites', q1_b: 'Tasting local flavors', q1_c: 'Spending time in nature', q1_d: 'Shopping',
    q2_text: 'What is your food preference?',
    q2_a: 'Traditional Turkish cuisine', q2_b: 'Street food', q2_c: 'Seafood', q2_d: 'International cuisine',
    q3_text: 'What is your budget level?',
    q3_a: 'Budget-friendly', q3_b: 'Moderate', q3_c: 'Comfortable', q3_d: 'Luxury',
    q4_text: 'How much can you walk per day?',
    q4_a: 'Very little, I like breaks', q4_b: 'A few hours', q4_c: 'I enjoy long walks', q4_d: 'I can walk all day',
    q5_text: 'Who are you traveling with?',
    q5_a: 'Alone', q5_b: 'With my partner', q5_c: 'With my family', q5_d: 'With friends',
    q6_text: 'What time of day do you prefer?',
    q6_a: 'Early morning', q6_b: 'Midday', q6_c: 'Evening', q6_d: 'Nightlife',
    q7_text: 'How important is photography to you?',
    q7_a: 'Very important, I capture every moment', q7_b: 'I shoot at special places', q7_c: 'Rarely', q7_d: "I don't take photos, I enjoy the moment",
    q8_text: 'How interested are you in history and architecture?',
    q8_a: 'Very interested, I love the details', q8_b: 'I want to see the major sites', q8_c: 'Somewhat interested', q8_d: 'Not really interested',
    q9_text: 'How much do you want to try local cuisine?',
    q9_a: 'I want to try everything', q9_b: "I'll try popular dishes", q9_c: 'I prefer familiar flavors', q9_d: 'I stick to my own food habits',
    q10_text: 'Do sea and Bosphorus activities appeal to you?',
    q10_a: 'Absolutely, I love it', q10_b: 'Yes, that would be nice', q10_c: "Doesn't matter", q10_d: 'No, I prefer land',
    q11_text: 'Do you enjoy shopping?',
    q11_a: 'Love it, I visit every shop', q11_b: 'I buy souvenirs', q11_c: 'Only if needed', q11_d: "I don't really shop",
    q12_text: 'How many days will you stay in Istanbul?',
    q12_a: '1-2 days', q12_b: '3-4 days', q12_c: '5-7 days', q12_d: 'More than a week',
    q13_text: 'What is your place preference?',
    q13_a: 'Crowded and lively places', q13_b: 'Popular but balanced', q13_c: 'Calm and peaceful', q13_d: 'Undiscovered hidden gems',
    q14_text: 'Are you interested in art and museums?',
    q14_a: 'Very much, I do museum tours', q14_b: 'I visit major museums', q14_c: 'Sometimes', q14_d: 'Not really',
    q15_text: 'Which best describes your travel style?',
    q15_a: 'Planned and organized', q15_b: 'Mixed, both planned and spontaneous', q15_c: 'Completely spontaneous and adventurous', q15_d: 'Relaxed and stress-free',

    result_badge: 'YOUR PROFILE',
    result_see_guide: 'See My Guide',
    result_retake: 'Retake Quiz',

    profile_historian_name: 'History Lover',
    profile_historian_desc: "You love discovering historical sites and cultural treasures. Istanbul's thousands of years of history await you!",
    profile_foodie_name: 'Gourmet Traveler',
    profile_foodie_desc: "Your palate is well-refined! Discovering Istanbul's unique cuisine is the greatest adventure for you.",
    profile_nature_name: 'Nature Enthusiast',
    profile_nature_desc: "Peaceful parks, sea views and green spaces are perfect for you. Istanbul's natural beauty will enchant you!",
    profile_shopper_name: 'Shopping Enthusiast',
    profile_shopper_desc: "Bazaars, boutiques and shops are your natural habitat. Istanbul is a shopping paradise for you!",
    profile_explorer_name: 'Explorer Spirit',
    profile_explorer_desc: "Discovering unknown streets, finding hidden corners and having adventures is your style!",

    cat_history: 'History & Culture',
    cat_food: 'Gastronomy',
    cat_nature: 'Nature & Peace',
    cat_shopping: 'Shopping & Fun',
    cat_adventure: 'Discovery & Adventure',

    guide_title: 'Your Travel Guide',
    guide_subtitle_prefix: 'Recommendations based on your profile:',
    tab_recommended: 'Recommended', tab_popular: 'Most Popular', tab_food: 'Food', tab_all: 'All',
    food_all: 'All', food_restaurant: 'Restaurant', food_fastfood: 'Fast Food', food_cafe: 'Cafe', food_dessert: 'Dessert',

    detail_back: 'Back', detail_rating: 'Rating', detail_price: 'Price', detail_popularity: 'Popularity',
    detail_about: 'About', detail_info: 'Practical Info', detail_signature: 'Signature Dishes',
    detail_tips: 'Tips', detail_nearby: 'Nearby Places', detail_hours: 'Visit Hours',
    detail_entrance: 'Entrance Fee', detail_transport: 'Transport',
    detail_free: 'Free', detail_very_popular: 'Very Popular', detail_popular: 'Popular', detail_moderate: 'Moderate',
    footer_text: 'All rights reserved'
},

/* ╔═══════════════════════════╗
   ║       DEUTSCH (DE)        ║
   ╚═══════════════════════════╝ */
de: {
    welcome_badge: 'PERSÖNLICHER REISEFÜHRER',
    welcome_title_1: 'Entdecken Sie',
    welcome_title_2: 'Istanbul',
    welcome_desc: 'Machen Sie unser 15-Fragen-Quiz und erhalten Sie Ihren persönlichen Reiseführer. Top-Sehenswürdigkeiten, Restaurants, Cafés und mehr!',
    welcome_f1: '15-Fragen-Quiz',
    welcome_f2: 'Persönlicher Führer',
    welcome_f3: 'Essensführer',
    welcome_f4: 'Beliebte Orte',
    welcome_lang_prompt: 'Wählen Sie Ihre Sprache',
    welcome_start: 'Quiz starten',

    quiz_home: 'Startseite', quiz_prev: 'Zurück', quiz_next: 'Weiter', quiz_finish: 'Quiz beenden',

    q1_text: 'Was genießen Sie im Urlaub am meisten?',
    q1_a: 'Historische Stätten besuchen', q1_b: 'Lokale Aromen probieren', q1_c: 'Zeit in der Natur verbringen', q1_d: 'Einkaufen gehen',
    q2_text: 'Was ist Ihre Essenspräferenz?',
    q2_a: 'Traditionelle türkische Küche', q2_b: 'Straßenessen', q2_c: 'Meeresfrüchte', q2_d: 'Internationale Küche',
    q3_text: 'Wie hoch ist Ihr Budget?',
    q3_a: 'Günstig', q3_b: 'Mittel', q3_c: 'Komfortabel', q3_d: 'Luxus',
    q4_text: 'Wie viel können Sie pro Tag laufen?',
    q4_a: 'Sehr wenig, ich mache gerne Pausen', q4_b: 'Ein paar Stunden', q4_c: 'Ich genieße lange Spaziergänge', q4_d: 'Ich kann den ganzen Tag laufen',
    q5_text: 'Mit wem reisen Sie?',
    q5_a: 'Allein', q5_b: 'Mit meinem Partner', q5_c: 'Mit meiner Familie', q5_d: 'Mit Freunden',
    q6_text: 'Welche Tageszeit bevorzugen Sie?',
    q6_a: 'Früher Morgen', q6_b: 'Mittag', q6_c: 'Abend', q6_d: 'Nachtleben',
    q7_text: 'Wie wichtig ist Ihnen Fotografie?',
    q7_a: 'Sehr wichtig, ich halte jeden Moment fest', q7_b: 'An besonderen Orten', q7_c: 'Selten', q7_d: 'Gar nicht, ich genieße den Moment',
    q8_text: 'Wie interessiert sind Sie an Geschichte und Architektur?',
    q8_a: 'Sehr, ich liebe Details', q8_b: 'Ich möchte die wichtigsten Orte sehen', q8_c: 'Etwas interessiert', q8_d: 'Nicht wirklich',
    q9_text: 'Wie sehr möchten Sie die lokale Küche probieren?',
    q9_a: 'Ich möchte alles probieren', q9_b: 'Beliebte Gerichte', q9_c: 'Vertraute Geschmäcker', q9_d: 'Eigene Essgewohnheiten',
    q10_text: 'Reizen Sie Meer- und Bosporus-Aktivitäten?',
    q10_a: 'Absolut, ich liebe es', q10_b: 'Ja, das wäre schön', q10_c: 'Egal', q10_d: 'Nein, ich bevorzuge das Land',
    q11_text: 'Gehen Sie gerne einkaufen?',
    q11_a: 'Sehr gerne, überall', q11_b: 'Souvenirs kaufen', q11_c: 'Nur wenn nötig', q11_d: 'Kaum',
    q12_text: 'Wie viele Tage bleiben Sie in Istanbul?',
    q12_a: '1-2 Tage', q12_b: '3-4 Tage', q12_c: '5-7 Tage', q12_d: 'Mehr als eine Woche',
    q13_text: 'Welche Art von Orten bevorzugen Sie?',
    q13_a: 'Belebte und lebhafte Orte', q13_b: 'Beliebt aber ausgewogen', q13_c: 'Ruhig und friedlich', q13_d: 'Unentdeckte Geheimtipps',
    q14_text: 'Interessieren Sie sich für Kunst und Museen?',
    q14_a: 'Sehr, ich mache Museumstouren', q14_b: 'Wichtige Museen', q14_c: 'Manchmal', q14_d: 'Nicht wirklich',
    q15_text: 'Welcher Reisestil beschreibt Sie am besten?',
    q15_a: 'Geplant und organisiert', q15_b: 'Gemischt', q15_c: 'Völlig spontan und abenteuerlich', q15_d: 'Entspannt und stressfrei',

    result_badge: 'IHR PROFIL',
    result_see_guide: 'Meinen Führer ansehen',
    result_retake: 'Quiz wiederholen',

    profile_historian_name: 'Geschichtsliebhaber',
    profile_historian_desc: 'Sie lieben es, historische Stätten und kulturelle Schätze zu entdecken. Istanbuls jahrtausendealte Geschichte erwartet Sie!',
    profile_foodie_name: 'Gourmet-Reisender',
    profile_foodie_desc: 'Ihr Gaumen ist sehr verfeinert! Istanbuls einzigartige Küche zu entdecken ist Ihr größtes Abenteuer.',
    profile_nature_name: 'Naturliebhaber',
    profile_nature_desc: 'Friedliche Parks, Meerblick und grüne Flächen sind perfekt für Sie. Istanbuls natürliche Schönheit wird Sie verzaubern!',
    profile_shopper_name: 'Shopping-Enthusiast',
    profile_shopper_desc: 'Basare, Boutiquen und Geschäfte sind Ihr natürlicher Lebensraum. Istanbul ist ein Einkaufsparadies!',
    profile_explorer_name: 'Entdecker-Geist',
    profile_explorer_desc: 'Unbekannte Straßen entdecken, versteckte Ecken finden und Abenteuer erleben ist Ihr Stil!',

    cat_history: 'Geschichte & Kultur', cat_food: 'Gastronomie', cat_nature: 'Natur & Ruhe',
    cat_shopping: 'Einkaufen & Unterhaltung', cat_adventure: 'Entdeckung & Abenteuer',

    guide_title: 'Ihr Reiseführer',
    guide_subtitle_prefix: 'Empfehlungen basierend auf Ihrem Profil:',
    tab_recommended: 'Empfohlen', tab_popular: 'Am beliebtesten', tab_food: 'Essen', tab_all: 'Alle',
    food_all: 'Alle', food_restaurant: 'Restaurant', food_fastfood: 'Fast Food', food_cafe: 'Café', food_dessert: 'Dessert',

    detail_back: 'Zurück', detail_rating: 'Bewertung', detail_price: 'Preis', detail_popularity: 'Beliebtheit',
    detail_about: 'Über', detail_info: 'Praktische Infos', detail_signature: 'Spezialitäten',
    detail_tips: 'Tipps', detail_nearby: 'In der Nähe', detail_hours: 'Besuchszeiten',
    detail_entrance: 'Eintritt', detail_transport: 'Anfahrt',
    detail_free: 'Kostenlos', detail_very_popular: 'Sehr beliebt', detail_popular: 'Beliebt', detail_moderate: 'Mittel',
    footer_text: 'Alle Rechte vorbehalten'
},

/* ╔═══════════════════════════╗
   ║      FRANÇAIS (FR)        ║
   ╚═══════════════════════════╝ */
fr: {
    welcome_badge: 'GUIDE DE VOYAGE PERSONNEL',
    welcome_title_1: 'Découvrez',
    welcome_title_2: 'Istanbul',
    welcome_desc: 'Répondez à notre quiz de 15 questions et obtenez votre guide de voyage personnalisé. Attractions, restaurants, cafés et plus!',
    welcome_f1: 'Quiz 15 Questions',
    welcome_f2: 'Guide Personnel',
    welcome_f3: 'Guide Culinaire',
    welcome_f4: 'Lieux Populaires',
    welcome_lang_prompt: 'Choisissez votre langue',
    welcome_start: 'Commencer le Quiz',

    quiz_home: 'Accueil', quiz_prev: 'Précédent', quiz_next: 'Suivant', quiz_finish: 'Terminer le Quiz',

    q1_text: "Qu'appréciez-vous le plus en vacances ?",
    q1_a: 'Visiter des sites historiques', q1_b: 'Goûter les saveurs locales', q1_c: 'Passer du temps dans la nature', q1_d: 'Faire du shopping',
    q2_text: 'Quelle est votre préférence culinaire ?',
    q2_a: 'Cuisine turque traditionnelle', q2_b: 'Street food', q2_c: 'Fruits de mer', q2_d: 'Cuisine internationale',
    q3_text: 'Quel est votre niveau de budget ?',
    q3_a: 'Économique', q3_b: 'Moyen', q3_c: 'Confortable', q3_d: 'Luxe',
    q4_text: 'Combien pouvez-vous marcher par jour ?',
    q4_a: 'Très peu, j\'aime les pauses', q4_b: 'Quelques heures', q4_c: 'J\'aime les longues promenades', q4_d: 'Toute la journée',
    q5_text: 'Avec qui voyagez-vous ?',
    q5_a: 'Seul(e)', q5_b: 'Avec mon partenaire', q5_c: 'En famille', q5_d: 'Entre amis',
    q6_text: 'Quel moment de la journée préférez-vous ?',
    q6_a: 'Tôt le matin', q6_b: 'En milieu de journée', q6_c: 'En soirée', q6_d: 'Vie nocturne',
    q7_text: 'Quelle importance accordez-vous à la photographie ?',
    q7_a: 'Très importante, je capture chaque moment', q7_b: 'Dans les endroits spéciaux', q7_c: 'Rarement', q7_d: 'Jamais, je profite du moment',
    q8_text: "Quel est votre intérêt pour l'histoire et l'architecture ?",
    q8_a: 'Très intéressé(e), j\'adore les détails', q8_b: 'Je veux voir les sites majeurs', q8_c: 'Un peu intéressé(e)', q8_d: 'Pas vraiment',
    q9_text: 'Voulez-vous essayer la cuisine locale ?',
    q9_a: 'Je veux tout essayer', q9_b: 'Les plats populaires', q9_c: 'Des saveurs familières', q9_d: 'Mes propres habitudes alimentaires',
    q10_text: 'Les activités maritimes et du Bosphore vous attirent-elles ?',
    q10_a: 'Absolument, j\'adore', q10_b: 'Oui, ce serait bien', q10_c: 'Peu importe', q10_d: 'Non, je préfère la terre ferme',
    q11_text: 'Aimez-vous faire du shopping ?',
    q11_a: 'J\'adore, je visite chaque boutique', q11_b: 'J\'achète des souvenirs', q11_c: 'Seulement si nécessaire', q11_d: 'Pas vraiment',
    q12_text: 'Combien de jours resterez-vous à Istanbul ?',
    q12_a: '1-2 jours', q12_b: '3-4 jours', q12_c: '5-7 jours', q12_d: 'Plus d\'une semaine',
    q13_text: 'Quel type de lieu préférez-vous ?',
    q13_a: 'Animés et vivants', q13_b: 'Populaires mais équilibrés', q13_c: 'Calmes et paisibles', q13_d: 'Des perles cachées',
    q14_text: "L'art et les musées vous intéressent-ils ?",
    q14_a: 'Beaucoup, je fais des visites de musées', q14_b: 'Les musées importants', q14_c: 'Parfois', q14_d: 'Pas vraiment',
    q15_text: 'Quel style de voyage vous décrit le mieux ?',
    q15_a: 'Planifié et organisé', q15_b: 'Mixte', q15_c: 'Totalement spontané et aventureux', q15_d: 'Détendu et sans stress',

    result_badge: 'VOTRE PROFIL',
    result_see_guide: 'Voir mon guide',
    result_retake: 'Refaire le quiz',

    profile_historian_name: "Passionné d'Histoire",
    profile_historian_desc: "Vous adorez découvrir les sites historiques et les trésors culturels. L'histoire millénaire d'Istanbul vous attend !",
    profile_foodie_name: 'Voyageur Gourmet',
    profile_foodie_desc: "Votre palais est très raffiné ! Découvrir la cuisine unique d'Istanbul est votre plus grande aventure.",
    profile_nature_name: 'Amoureux de la Nature',
    profile_nature_desc: "Parcs paisibles, vues sur la mer et espaces verts sont faits pour vous. La beauté naturelle d'Istanbul vous enchantera !",
    profile_shopper_name: 'Passionné de Shopping',
    profile_shopper_desc: "Bazars, boutiques et magasins sont votre habitat naturel. Istanbul est un paradis du shopping pour vous !",
    profile_explorer_name: 'Esprit Explorateur',
    profile_explorer_desc: "Découvrir des rues inconnues, trouver des coins cachés et vivre des aventures, c'est votre style !",

    cat_history: 'Histoire & Culture', cat_food: 'Gastronomie', cat_nature: 'Nature & Paix',
    cat_shopping: 'Shopping & Divertissement', cat_adventure: 'Découverte & Aventure',

    guide_title: 'Votre Guide de Voyage',
    guide_subtitle_prefix: 'Recommandations selon votre profil :',
    tab_recommended: 'Recommandé', tab_popular: 'Plus Populaires', tab_food: 'Nourriture', tab_all: 'Tout',
    food_all: 'Tout', food_restaurant: 'Restaurant', food_fastfood: 'Fast Food', food_cafe: 'Café', food_dessert: 'Pâtisserie',

    detail_back: 'Retour', detail_rating: 'Note', detail_price: 'Prix', detail_popularity: 'Popularité',
    detail_about: 'À propos', detail_info: 'Infos Pratiques', detail_signature: 'Spécialités',
    detail_tips: 'Conseils', detail_nearby: 'À proximité', detail_hours: 'Horaires de visite',
    detail_entrance: "Droit d'entrée", detail_transport: 'Transport',
    detail_free: 'Gratuit', detail_very_popular: 'Très populaire', detail_popular: 'Populaire', detail_moderate: 'Modéré',
    footer_text: 'Tous droits réservés'
},

/* ╔═══════════════════════════╗
   ║      العربية (AR)          ║
   ╚═══════════════════════════╝ */
ar: {
    welcome_badge: 'دليل السفر الشخصي',
    welcome_title_1: 'اكتشف',
    welcome_title_2: 'إسطنبول',
    welcome_desc: 'أجب على اختبارنا المكون من 15 سؤالاً واحصل على دليل سفرك المخصص. أشهر المعالم والمطاعم والمقاهي والمزيد!',
    welcome_f1: 'اختبار 15 سؤال',
    welcome_f2: 'دليل شخصي',
    welcome_f3: 'دليل الطعام',
    welcome_f4: 'أماكن شهيرة',
    welcome_lang_prompt: 'اختر لغتك',
    welcome_start: 'ابدأ الاختبار',

    quiz_home: 'الرئيسية', quiz_prev: 'السابق', quiz_next: 'التالي', quiz_finish: 'إنهاء الاختبار',

    q1_text: 'ما الذي تستمتع به أكثر في الإجازة؟',
    q1_a: 'زيارة المواقع التاريخية', q1_b: 'تذوق النكهات المحلية', q1_c: 'قضاء الوقت في الطبيعة', q1_d: 'التسوق',
    q2_text: 'ما هو تفضيلك في الطعام؟',
    q2_a: 'المطبخ التركي التقليدي', q2_b: 'طعام الشارع', q2_c: 'المأكولات البحرية', q2_d: 'المطبخ العالمي',
    q3_text: 'ما هو مستوى ميزانيتك؟',
    q3_a: 'اقتصادي', q3_b: 'متوسط', q3_c: 'مريح', q3_d: 'فاخر',
    q4_text: 'كم يمكنك المشي في اليوم؟',
    q4_a: 'قليل جداً، أحب الاستراحة', q4_b: 'بضع ساعات', q4_c: 'أحب المشي الطويل', q4_d: 'أستطيع المشي طوال اليوم',
    q5_text: 'مع من تسافر؟',
    q5_a: 'بمفردي', q5_b: 'مع شريكي', q5_c: 'مع عائلتي', q5_d: 'مع أصدقائي',
    q6_text: 'أي وقت من اليوم تفضل؟',
    q6_a: 'الصباح الباكر', q6_b: 'وقت الظهيرة', q6_c: 'المساء', q6_d: 'الحياة الليلية',
    q7_text: 'ما مدى أهمية التصوير بالنسبة لك؟',
    q7_a: 'مهم جداً، أصور كل لحظة', q7_b: 'في الأماكن المميزة', q7_c: 'نادراً', q7_d: 'لا أصور، أستمتع باللحظة',
    q8_text: 'ما مدى اهتمامك بالتاريخ والعمارة؟',
    q8_a: 'مهتم جداً، أحب التفاصيل', q8_b: 'أريد رؤية المواقع الرئيسية', q8_c: 'مهتم قليلاً', q8_d: 'غير مهتم',
    q9_text: 'ما مدى رغبتك في تجربة المطبخ المحلي؟',
    q9_a: 'أريد تجربة كل شيء', q9_b: 'الأطباق الشهيرة', q9_c: 'نكهات مألوفة', q9_d: 'عاداتي الغذائية الخاصة',
    q10_text: 'هل تجذبك الأنشطة البحرية والبوسفور؟',
    q10_a: 'بالتأكيد، أحبها كثيراً', q10_b: 'نعم، سيكون جميلاً', q10_c: 'لا يهم', q10_d: 'لا، أفضل البر',
    q11_text: 'هل تحب التسوق؟',
    q11_a: 'أحبه كثيراً، أزور كل مكان', q11_b: 'أشتري الهدايا التذكارية', q11_c: 'فقط عند الحاجة', q11_d: 'لا أتسوق كثيراً',
    q12_text: 'كم يوماً ستبقى في إسطنبول؟',
    q12_a: 'يوم أو يومين', q12_b: '3-4 أيام', q12_c: '5-7 أيام', q12_d: 'أكثر من أسبوع',
    q13_text: 'ما تفضيلك للأماكن؟',
    q13_a: 'أماكن مزدحمة وحيوية', q13_b: 'شعبية ولكن متوازنة', q13_c: 'هادئة ومسالمة', q13_d: 'جواهر مخفية غير مكتشفة',
    q14_text: 'هل تهتم بالفن والمتاحف؟',
    q14_a: 'كثيراً، أقوم بجولات في المتاحف', q14_b: 'المتاحف المهمة', q14_c: 'أحياناً', q14_d: 'ليس حقاً',
    q15_text: 'أي أسلوب سفر يصفك بشكل أفضل؟',
    q15_a: 'مخطط ومنظم', q15_b: 'مزيج بين المخطط والعفوي', q15_c: 'عفوي تماماً ومغامر', q15_d: 'مسترخٍ وبدون توتر',

    result_badge: 'ملفك الشخصي',
    result_see_guide: 'عرض دليلي',
    result_retake: 'إعادة الاختبار',

    profile_historian_name: 'عاشق التاريخ',
    profile_historian_desc: 'أنت تحب اكتشاف المواقع التاريخية والكنوز الثقافية. تاريخ إسطنبول الممتد لآلاف السنين ينتظرك!',
    profile_foodie_name: 'المسافر الذواق',
    profile_foodie_desc: 'ذوقك في الطعام راقٍ جداً! اكتشاف مطبخ إسطنبول الفريد هو أعظم مغامرة لك.',
    profile_nature_name: 'محب الطبيعة',
    profile_nature_desc: 'الحدائق الهادئة وإطلالات البحر والمساحات الخضراء مثالية لك. جمال إسطنبول الطبيعي سيسحرك!',
    profile_shopper_name: 'عاشق التسوق',
    profile_shopper_desc: 'البازارات والمتاجر والمحلات هي موطنك الطبيعي. إسطنبول جنة التسوق بالنسبة لك!',
    profile_explorer_name: 'روح المستكشف',
    profile_explorer_desc: 'اكتشاف شوارع مجهولة وإيجاد زوايا مخفية وعيش المغامرات هو أسلوبك!',

    cat_history: 'التاريخ والثقافة', cat_food: 'فن الطهي', cat_nature: 'الطبيعة والسكينة',
    cat_shopping: 'التسوق والترفيه', cat_adventure: 'الاستكشاف والمغامرة',

    guide_title: 'دليل سفرك',
    guide_subtitle_prefix: 'توصيات بناءً على ملفك الشخصي:',
    tab_recommended: 'موصى به', tab_popular: 'الأكثر شهرة', tab_food: 'الطعام', tab_all: 'الكل',
    food_all: 'الكل', food_restaurant: 'مطعم', food_fastfood: 'وجبات سريعة', food_cafe: 'مقهى', food_dessert: 'حلويات',

    detail_back: 'رجوع', detail_rating: 'التقييم', detail_price: 'السعر', detail_popularity: 'الشعبية',
    detail_about: 'حول', detail_info: 'معلومات عملية', detail_signature: 'الأطباق المميزة',
    detail_tips: 'نصائح', detail_nearby: 'أماكن قريبة', detail_hours: 'ساعات الزيارة',
    detail_entrance: 'رسوم الدخول', detail_transport: 'المواصلات',
    detail_free: 'مجاني', detail_very_popular: 'شائع جداً', detail_popular: 'شائع', detail_moderate: 'متوسط',
    footer_text: 'جميع الحقوق محفوظة'
},

/* ╔═══════════════════════════╗
   ║       РУССКИЙ (RU)        ║
   ╚═══════════════════════════╝ */
ru: {
    welcome_badge: 'ПЕРСОНАЛЬНЫЙ ГАЙД',
    welcome_title_1: 'Откройте для себя',
    welcome_title_2: 'Стамбул',
    welcome_desc: 'Пройдите наш тест из 15 вопросов и получите персональный путеводитель. Лучшие достопримечательности, рестораны, кафе и многое другое!',
    welcome_f1: 'Тест 15 вопросов',
    welcome_f2: 'Личный гид',
    welcome_f3: 'Гид по еде',
    welcome_f4: 'Популярные места',
    welcome_lang_prompt: 'Выберите язык',
    welcome_start: 'Начать тест',

    quiz_home: 'Главная', quiz_prev: 'Назад', quiz_next: 'Далее', quiz_finish: 'Завершить тест',

    q1_text: 'Что вам больше всего нравится в отпуске?',
    q1_a: 'Посещать исторические места', q1_b: 'Пробовать местные блюда', q1_c: 'Проводить время на природе', q1_d: 'Шоппинг',
    q2_text: 'Каковы ваши предпочтения в еде?',
    q2_a: 'Традиционная турецкая кухня', q2_b: 'Уличная еда', q2_c: 'Морепродукты', q2_d: 'Международная кухня',
    q3_text: 'Каков ваш уровень бюджета?',
    q3_a: 'Экономный', q3_b: 'Средний', q3_c: 'Комфортный', q3_d: 'Люкс',
    q4_text: 'Сколько вы можете ходить пешком в день?',
    q4_a: 'Очень мало, люблю отдыхать', q4_b: 'Несколько часов', q4_c: 'Люблю долгие прогулки', q4_d: 'Могу ходить весь день',
    q5_text: 'С кем вы путешествуете?',
    q5_a: 'Один/одна', q5_b: 'С партнёром', q5_c: 'С семьёй', q5_d: 'С друзьями',
    q6_text: 'Какое время суток вы предпочитаете?',
    q6_a: 'Раннее утро', q6_b: 'Полдень', q6_c: 'Вечер', q6_d: 'Ночная жизнь',
    q7_text: 'Насколько важна для вас фотография?',
    q7_a: 'Очень важна, снимаю каждый момент', q7_b: 'В особых местах', q7_c: 'Редко', q7_d: 'Не фотографирую, наслаждаюсь моментом',
    q8_text: 'Насколько вас интересует история и архитектура?',
    q8_a: 'Очень, люблю детали', q8_b: 'Хочу увидеть главные места', q8_c: 'Немного интересует', q8_d: 'Не особо',
    q9_text: 'Насколько вы хотите попробовать местную кухню?',
    q9_a: 'Хочу попробовать всё', q9_b: 'Популярные блюда', q9_c: 'Знакомые вкусы', q9_d: 'Свои пищевые привычки',
    q10_text: 'Привлекают ли вас морские прогулки и Босфор?',
    q10_a: 'Определённо, обожаю', q10_b: 'Да, было бы здорово', q10_c: 'Не важно', q10_d: 'Нет, предпочитаю сушу',
    q11_text: 'Любите ли вы шоппинг?',
    q11_a: 'Обожаю, захожу всюду', q11_b: 'Покупаю сувениры', q11_c: 'Только при необходимости', q11_d: 'Не особо',
    q12_text: 'Сколько дней вы проведёте в Стамбуле?',
    q12_a: '1-2 дня', q12_b: '3-4 дня', q12_c: '5-7 дней', q12_d: 'Больше недели',
    q13_text: 'Какие места вы предпочитаете?',
    q13_a: 'Оживлённые и шумные', q13_b: 'Популярные, но сбалансированные', q13_c: 'Тихие и спокойные', q13_d: 'Неизведанные скрытые жемчужины',
    q14_text: 'Интересуют ли вас искусство и музеи?',
    q14_a: 'Очень, хожу на экскурсии по музеям', q14_b: 'Важные музеи', q14_c: 'Иногда', q14_d: 'Не особо',
    q15_text: 'Какой стиль путешествия вас описывает лучше всего?',
    q15_a: 'Спланированный и организованный', q15_b: 'Смешанный', q15_c: 'Полностью спонтанный и авантюрный', q15_d: 'Расслабленный и без стресса',

    result_badge: 'ВАШ ПРОФИЛЬ',
    result_see_guide: 'Показать мой гид',
    result_retake: 'Пройти тест снова',

    profile_historian_name: 'Любитель истории',
    profile_historian_desc: 'Вы любите открывать исторические места и культурные сокровища. Тысячелетняя история Стамбула ждёт вас!',
    profile_foodie_name: 'Гурман-путешественник',
    profile_foodie_desc: 'У вас утончённый вкус! Открытие уникальной кухни Стамбула — ваше главное приключение.',
    profile_nature_name: 'Любитель природы',
    profile_nature_desc: 'Тихие парки, морские виды и зелёные пространства идеальны для вас. Природная красота Стамбула вас очарует!',
    profile_shopper_name: 'Любитель шоппинга',
    profile_shopper_desc: 'Базары, бутики и магазины — ваша естественная среда. Стамбул — рай для шоппинга!',
    profile_explorer_name: 'Дух исследователя',
    profile_explorer_desc: 'Открывать неизвестные улицы, находить скрытые уголки и переживать приключения — ваш стиль!',

    cat_history: 'История и культура', cat_food: 'Гастрономия', cat_nature: 'Природа и покой',
    cat_shopping: 'Шоппинг и развлечения', cat_adventure: 'Открытия и приключения',

    guide_title: 'Ваш путеводитель',
    guide_subtitle_prefix: 'Рекомендации на основе вашего профиля:',
    tab_recommended: 'Рекомендуемое', tab_popular: 'Популярное', tab_food: 'Еда', tab_all: 'Всё',
    food_all: 'Всё', food_restaurant: 'Ресторан', food_fastfood: 'Фаст-фуд', food_cafe: 'Кафе', food_dessert: 'Десерты',

    detail_back: 'Назад', detail_rating: 'Рейтинг', detail_price: 'Цена', detail_popularity: 'Популярность',
    detail_about: 'О месте', detail_info: 'Практическая информация', detail_signature: 'Фирменные блюда',
    detail_tips: 'Советы', detail_nearby: 'Рядом', detail_hours: 'Часы посещения',
    detail_entrance: 'Входная плата', detail_transport: 'Транспорт',
    detail_free: 'Бесплатно', detail_very_popular: 'Очень популярно', detail_popular: 'Популярно', detail_moderate: 'Умеренно',
    footer_text: 'Все права защищены'
}

}; // end translations
